(()=>{
"use strict";
const KEY="inovtec_absences_v1",PLANNING_KEY="inovtec_plannings_v2",$=id=>document.getElementById(id),pad=n=>String(n).padStart(2,"0");
const uid=()=>"leave_"+Date.now().toString(16)+"_"+Math.random().toString(16).slice(2),now=()=>new Date().toISOString(),stamp=x=>JSON.stringify(x||null);
const norm=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const parentWin=(()=>{try{return parent&&parent!==window?parent:window}catch{return window}})(),fb=()=>{try{return parentWin.firebase||window.firebase}catch{return null}},hub=()=>{try{return parentWin.InovtecDataHub||null}catch{return null}};
const parse=(s,f)=>{try{return JSON.parse(s)??f}catch{return f}};
let leaves=[],records=[],agents=[],month=new Date(new Date().getFullYear(),new Date().getMonth(),1),user=null,ref=null,unsub=null,hubUnsub=null,ready=false,busy=false,migrating=false,authBound=false,editingRevision=null;
function cache(){try{const a=parse(localStorage.getItem(KEY)||"[]",[]);return Array.isArray(a)?a:[]}catch{return[]}}
function cacheCloud(){try{localStorage.setItem(KEY,JSON.stringify(records))}catch(e){console.warn("Cache congés",e)}}
function dateISO(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function parseDate(s){const m=String(s||"").match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?new Date(+m[1],+m[2]-1,+m[3]):null}
function covers(l,date){const a=parseDate(l.startDate),b=parseDate(l.endDate),d=parseDate(date);return !!(a&&b&&d&&d>=a&&d<=b&&!l.deleted&&!['rejected','cancelled'].includes(l.status))}
function approved(l){return l.status==="approved"&&!l.deleted}
function name(a){return a?.name||a?.displayName||[a?.identity?.prenom,a?.identity?.nom].filter(Boolean).join(" ")||"Agent"}
function initials(s){return String(s||"?").split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join("")||"?"}
function tone(l){if(['rejected','cancelled','pending'].includes(l.status))return l.status;return /maladie|absence/i.test(l.type||"")||l.sourceType==="absence"?"sick":"approved"}
function statusText(s){return s==="pending"?"À valider":s==="approved"?"Validée":s==="rejected"?"Refusée":"Annulée"}
function partText(s){return s==="morning"?"matin":s==="afternoon"?"après-midi":"journée complète"}
function fmtDate(s){const d=parseDate(s);return d?new Intl.DateTimeFormat("fr-FR",{day:"numeric",month:"short",year:"numeric"}).format(d):"—"}
function planning(){const p=parse(localStorage.getItem(PLANNING_KEY)||"{}",{});return p&&p.weeks?p:{agents:[],weeks:{}}}
function dateFromWeek(key,day){const m=String(key).match(/^(\d{4})-W(\d{2})$/);if(!m)return null;const y=+m[1],w=+m[2],jan4=new Date(y,0,4),offset=(jan4.getDay()+6)%7,mon=new Date(y,0,4-offset);mon.setDate(mon.getDate()+(w-1)*7+(Number(day)||0));return mon}
function coverage(l){if(!approved(l))return{total:0,replaced:0,pending:0};const p=planning(),n=norm(l.agentName),a=(p.agents||[]).find(x=>String(x.refId||x.id)===String(l.agentRefId)||(norm(x.name)===n));if(!a)return{total:0,replaced:0,pending:0};let replaced=0,pending=0;Object.entries(p.weeks||{}).forEach(([w,rows])=>(rows||[]).forEach(e=>{if(e?._replacementFor?.leaveId===l.id)replaced++;else if(String(e.agentId)===String(a.id)){const d=dateFromWeek(w,e.day);if(d&&covers(l,dateISO(d)))pending++}}));return{total:replaced+pending,replaced,pending}}
function message(t,bad=false){const e=$("congesSyncStatus");if(e){e.textContent=t;e.style.color=bad?"#ad382d":"#0b6b43"}}
function refresh(connected,label){ready=connected;message(label,!connected);render()}
function kpis(){const day=dateISO(new Date()),today=parseDate(day);$("kpiToday").textContent=leaves.filter(l=>approved(l)&&covers(l,day)).length;$("kpiPending").textContent=leaves.filter(l=>l.status==="pending").length;$("kpiUpcoming").textContent=leaves.filter(l=>approved(l)&&parseDate(l.startDate)>today).length;$("kpiCoverage").textContent=leaves.reduce((n,l)=>n+coverage(l).pending,0)}
function agentSelect(){const el=$("agentSelect"),value=el.value;el.innerHTML='<option value="">Choisir un agent…</option>';agents.forEach(a=>{const o=document.createElement("option");o.value=a.id;o.textContent=name(a);el.appendChild(o)});if([...el.options].some(o=>o.value===value))el.value=value}
function timeline(){const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),first=dateISO(month),last=dateISO(new Date(month.getFullYear(),month.getMonth(),days));$("monthLabel").textContent=new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(month).replace(/^./,c=>c.toUpperCase());const root=document.createElement("div");root.className="timeline";root.style.setProperty("--days",days);const head=document.createElement("div");head.className="timeline-head";head.innerHTML='<div class="timeline-agent-head">Agents</div>';for(let i=1;i<=days;i++){const d=new Date(month.getFullYear(),month.getMonth(),i),el=document.createElement("div");el.className="day-h";el.innerHTML=`<span>${new Intl.DateTimeFormat("fr-FR",{weekday:"short"}).format(d).replace(".","")}</span><strong>${i}</strong>`;head.appendChild(el)}root.appendChild(head);
 const visible=agents.filter(a=>leaves.some(l=>String(l.agentRefId)===String(a.id)&&l.startDate<=last&&l.endDate>=first)),all=visible.length?visible:agents;for(const a of all){const row=document.createElement("div");row.className="timeline-row";const mine=leaves.filter(l=>String(l.agentRefId)===String(a.id)&&l.startDate<=last&&l.endDate>=first),ac=document.createElement("div");ac.className="timeline-agent";ac.innerHTML=`<div class="agent-avatar">${initials(name(a))}</div><div class="agent-copy"><strong></strong><small>${mine.length?mine.length+" période"+(mine.length>1?"s":""):"Disponible"}</small></div>`;ac.querySelector("strong").textContent=name(a);row.appendChild(ac);for(let d=1;d<=days;d++){const dt=new Date(month.getFullYear(),month.getMonth(),d),cell=document.createElement("div");cell.className="day-cell"+([0,6].includes(dt.getDay())?" weekend":"")+(dateISO(dt)===dateISO(new Date())?" today":"");row.appendChild(cell)}mine.forEach(l=>{const a=parseDate(l.startDate),b=parseDate(l.endDate);if(!a||!b)return;const s=Math.max(1,a.getMonth()===month.getMonth()&&a.getFullYear()===month.getFullYear()?a.getDate():1),e=Math.min(days,b.getMonth()===month.getMonth()&&b.getFullYear()===month.getFullYear()?b.getDate():days),band=document.createElement("button");band.type="button";band.className="leave-band "+tone(l);band.style.gridColumn=`${s+1} / ${e+2}`;band.style.gridRow="1";band.style.margin="9px 3px";band.style.position="relative";band.textContent=`${l.type} · ${statusText(l.status)}`;band.title=`${name(a)} — ${fmtDate(l.startDate)} → ${fmtDate(l.endDate)}`;band.onclick=()=>openEdit(l.id);row.appendChild(band)});root.appendChild(row)}$("timelineWrap").replaceChildren(root)}
function list(){const q=norm($("searchLeave").value),status=$("statusFilter").value,box=$("leaveList");box.replaceChildren();const filtered=leaves.filter(l=>(status==="all"||l.status===status)&&(!q||norm(l.agentName).includes(q)||norm(l.type).includes(q))).sort((a,b)=>String(b.startDate).localeCompare(String(a.startDate)));if(!filtered.length){box.innerHTML='<div class="empty">Aucune demande ou absence pour ce filtre.</div>';return}
 filtered.forEach(l=>{const cov=coverage(l),pct=cov.total?Math.round(cov.replaced/cov.total*100):0,row=document.createElement("div");row.className="leave-row";row.innerHTML=`<div class="leave-person"><div class="agent-avatar">${initials(l.agentName)}</div><div><strong></strong><small>${l.sourceType==="request"?"Demande":"Absence enregistrée"}</small></div></div><div class="leave-meta"><b></b><small>${fmtDate(l.startDate)} → ${fmtDate(l.endDate)}</small></div><div><span class="status-pill ${l.status}">${statusText(l.status)}</span><small style="display:block;color:#7c8982;font-size:9px;margin-top:4px">Début : ${partText(l.startPart)}</small></div><div class="coverage"><b>${approved(l)?`${cov.replaced} remplacée${cov.replaced>1?"s":""} · ${cov.pending} à couvrir`:"Remplacement après validation"}</b><div class="progress"><span style="width:${pct}%"></span></div><small>${cov.total?cov.total+" intervention"+(cov.total>1?"s":"")+" concernée"+(cov.total>1?"s":""):"Aucune intervention détectée"}</small></div><div class="row-actions"></div>`;row.querySelector(".leave-person strong").textContent=l.agentName;row.querySelector(".leave-meta b").textContent=l.type;
 const actions=row.querySelector(".row-actions"),action=(label,cls,fn)=>{const b=document.createElement("button");b.type="button";b.className="mini-btn "+cls;b.textContent=label;b.disabled=!ready||busy;b.onclick=fn;actions.appendChild(b)};if(l.status==="pending"){action("Valider","approve",()=>changeStatus(l,"approved"));action("Refuser","reject",()=>changeStatus(l,"rejected"))}else if(l.status==="approved")action("Annuler","reject",()=>changeStatus(l,"cancelled"));action("Modifier","",()=>openEdit(l.id));if(approved(l)&&cov.pending)action("Organiser","approve",()=>{try{parentWin.location.href=`inovtec-page-shell.html?mode=planning&page=PLANNINGS-LEGACY.html%3Fv%3D20260815-menu1&replacementAgent=${encodeURIComponent(l.agentRefId)}`}catch{location.href="PLANNINGS.html"}});box.appendChild(row)})}
function render(){leaves=records.filter(l=>l&&!l.deleted);kpis();timeline();list();agentSelect();$("newLeave").disabled=!ready||busy;const submit=$("leaveForm").querySelector('[type="submit"]');if(submit)submit.disabled=!ready||busy;$("deleteLeave").disabled=!ready||busy}
function openModal(l=null){if(!ready||busy)return;editingRevision=l?stamp(l):null;$("leaveModal").classList.add("open");$("leaveModal").setAttribute("aria-hidden","false");$("modalTitle").textContent=l?"Modifier la demande / absence":"Nouvelle demande / absence";$("leaveId").value=l?.id||"";$("agentSelect").value=l?.agentRefId||"";$("sourceType").value=l?.sourceType||"request";$("leaveType").value=l?.type||"Congés payés";$("startDate").value=l?.startDate||dateISO(new Date());$("endDate").value=l?.endDate||dateISO(new Date());$("startPart").value=l?.startPart||"full";$("endPart").value=l?.endPart||"full";$("leaveComment").value=l?.comment||"";$("deleteLeave").hidden=!l;updateHint();setTimeout(()=>$("agentSelect").focus(),20)}
function closeModal(){if(busy)return;$("leaveModal").classList.remove("open");$("leaveModal").setAttribute("aria-hidden","true");editingRevision=null}
function openEdit(id){const l=leaves.find(x=>x.id===id);if(l)openModal(l)}
function updateHint(){$("statusHint").textContent=$("sourceType").value==="absence"?"Une absence enregistrée est considérée comme validée immédiatement et peut déclencher les remplacements.":"Une demande de congé sera enregistrée « À valider » avant d’impacter le planning."}
function readRecords(doc){const entry=doc?.moduleSyncV1?.conges;if(!entry)return null;const list=parse(entry.payload||"[]",null);if(!Array.isArray(list))throw Error("Format des congés Firebase invalide : aucune écriture effectuée.");return list}
async function saveChange(kind,record,expected){if(!ready||busy||!ref||!user){message("Firebase non confirmé : aucune modification enregistrée.",true);return false}busy=true;render();message("Synchronisation Firebase…");const currentRef=ref,currentUid=user.uid;
 try{await fb().firestore().runTransaction(async tx=>{const snap=await tx.get(currentRef),cloud=snap.exists?readRecords(snap.data()):null;if(cloud===null&&kind!=="create")throw Error("Congés indisponibles : attendez la synchronisation.");const rows=cloud?cloud.slice():[],i=rows.findIndex(x=>String(x?.id)===String(record.id)),old=i>=0?rows[i]:null;if(kind==="create"&&old)throw Error("Cette demande existe déjà sur un autre appareil.");if(kind!=="create"&&(!old||old.deleted||stamp(old)!==expected))throw Error("Cette demande a été modifiée ou supprimée sur l’autre appareil. Ouvrez de nouveau sa fiche avant d’enregistrer.");if(kind==="delete")rows[i]={...old,deleted:true,status:"cancelled",updatedAt:now()};else if(kind==="status")rows[i]={...old,status:record.status,updatedAt:now()};else if(kind==="create")rows.push(record);else rows[i]={...old,...record};tx.set(currentRef,{moduleSyncV1:{conges:{payload:JSON.stringify(rows),updatedAtMs:Date.now(),client:"conges_"+currentUid.slice(0,6),reason:kind,version:2}}},{merge:true})});message("Firebase synchronisé");return true}
 catch(e){console.warn("Congés Firebase",e);message(e?.message||"Erreur Firebase : aucune modification enregistrée.",true);return false}finally{busy=false;render()}}
async function changeStatus(l,status){const ok=await saveChange("status",{id:l.id,status},stamp(l));if(!ok&&ready)alert($("congesSyncStatus").textContent)}
async function deleteCurrent(){const id=$("leaveId").value,l=leaves.find(x=>x.id===id);if(!l||!confirm("Supprimer cette demande / absence ?"))return;const ok=await saveChange("delete",{id},editingRevision);if(ok)closeModal();else alert($("congesSyncStatus").textContent)}
async function onSubmit(e){e.preventDefault();if(busy||!ready)return;const id=$("leaveId").value||uid(),refId=$("agentSelect").value,a=agents.find(x=>String(x.id)===String(refId));if(!a)return alert("Choisissez un agent.");const start=$("startDate").value,end=$("endDate").value;if(!start||!end||end<start)return alert("Vérifiez les dates de début et de fin.");const old=leaves.find(x=>x.id===id),sourceType=$("sourceType").value,status=old?.status||(sourceType==="absence"?"approved":"pending"),timestamp=now();const row={id,agentRefId:refId,agentName:name(a),sourceType,type:$("leaveType").value,startDate:start,endDate:end,startPart:$("startPart").value,endPart:$("endPart").value,comment:$("leaveComment").value.trim(),status:sourceType==="absence"&&status==="pending"?"approved":status,createdAt:old?.createdAt||timestamp,updatedAt:timestamp};const ok=await saveChange(old?"edit":"create",row,editingRevision);if(ok)closeModal();else alert($("congesSyncStatus").textContent)}
function bindHub(){const h=hub();if(!h){setTimeout(bindHub,350);return}agents=Array.from(h.agents||[]);render();try{hubUnsub?.()}catch{}if(h.subscribe)hubUnsub=h.subscribe(detail=>{agents=Array.from(detail.agents||[]);render()})}
function markSeen(){try{localStorage.setItem("inovtec_conges_cloud_seen_"+user.uid,"1");localStorage.setItem("inovtec_conges_cache_uid",user.uid)}catch{}}
async function migrateInitial(local,currentRef,currentUid){if(migrating||!local.length||!user||user.uid!==currentUid)return;migrating=true;message("Reprise des congés dans Firebase…");try{await fb().firestore().runTransaction(async tx=>{const snap=await tx.get(currentRef);if(snap.exists&&snap.data()?.moduleSyncV1?.conges)return;tx.set(currentRef,{moduleSyncV1:{conges:{payload:JSON.stringify(local),updatedAtMs:Date.now(),client:"migration_"+currentUid.slice(0,6),reason:"migration-initiale",version:2}}},{merge:true})})}catch(e){console.warn("Migration congés",e);message("Reprise impossible : données locales conservées, écriture bloquée.",true)}finally{migrating=false}}
function bindFirebase(){const f=fb();if(!f){refresh(false,"Firebase indisponible : aucune écriture possible.");setTimeout(bindFirebase,500);return}if(authBound)return;authBound=true;f.auth().onAuthStateChanged(u=>{if(unsub){try{unsub()}catch{}unsub=null}user=u||null;ref=null;ready=false;busy=false;records=[];if(!user){$("loginModal").classList.add("open");refresh(false,"Connexion requise : données non partagées.");return}$("loginModal").classList.remove("open");ref=f.firestore().collection("kanban").doc(user.uid);const currentUid=user.uid,currentRef=ref;refresh(false,"Connexion Firebase en cours…");unsub=ref.onSnapshot({includeMetadataChanges:true},snap=>{if(!user||user.uid!==currentUid)return;const confirmed=!(snap.metadata?.fromCache||snap.metadata?.hasPendingWrites);let remote;try{remote=snap.exists?readRecords(snap.data()):null}catch(e){refresh(false,e.message);return}if(remote===null){if(!confirmed){refresh(false,"Attente de confirmation Firebase…");return}const seen=localStorage.getItem("inovtec_conges_cloud_seen_"+currentUid)==="1",previousUid=localStorage.getItem("inovtec_conges_cache_uid"),local=cache();if(!seen&&(!previousUid||previousUid===currentUid)&&local.length){migrateInitial(local,currentRef,currentUid);return}records=[];cacheCloud();markSeen();refresh(true,"Firebase synchronisé");return}records=remote;cacheCloud();if(confirmed){markSeen();refresh(true,busy?"Synchronisation Firebase…":"Firebase synchronisé")}else refresh(false,"Attente de confirmation Firebase…")},e=>{console.warn("Lecture congés Firebase",e);refresh(false,"Firebase inaccessible : aucune écriture possible.")})})}
function bind(){const badge=document.createElement("div");badge.id="congesSyncStatus";badge.setAttribute("role","status");badge.setAttribute("aria-live","polite");badge.style.cssText="font:600 12px Inter,sans-serif;padding:8px 16px;color:#ad382d";$("timelineWrap").parentElement.prepend(badge);records=cache();render();bindHub();bindFirebase();$("prevMonth").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);timeline()};$("nextMonth").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);timeline()};$("monthLabel").onclick=()=>{month=new Date(new Date().getFullYear(),new Date().getMonth(),1);timeline()};$("newLeave").onclick=()=>openModal();$("closeModal").onclick=closeModal;$("cancelModal").onclick=closeModal;$("deleteLeave").onclick=deleteCurrent;$("leaveForm").onsubmit=onSubmit;$("sourceType").onchange=updateHint;$("searchLeave").oninput=list;$("statusFilter").onchange=list;$("leaveModal").addEventListener("click",e=>{if(e.target===$("leaveModal"))closeModal()});$("loginForm").onsubmit=async e=>{e.preventDefault();const f=fb(),err=$("loginError");err.textContent="";if(!f){err.textContent="Firebase indisponible.";return}try{try{await f.auth().setPersistence(f.auth.Auth.Persistence.LOCAL)}catch(_e1){try{await f.auth().setPersistence(f.auth.Auth.Persistence.SESSION)}catch(_e2){try{await f.auth().setPersistence(f.auth.Auth.Persistence.NONE)}catch(_e3){}}}await f.auth().signInWithEmailAndPassword($("loginEmail").value.trim(),$("loginPassword").value)}catch(ex){err.textContent="Connexion impossible : "+(ex?.message||"vérifiez vos identifiants.")}};window.__INOVTEC_CONGES_SYNC_V2__=true}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind);else bind();
})();