(()=>{
"use strict";
const KEY="inovtec_absences_v1",PLANNING_KEY="inovtec_plannings_v2";
const $=id=>document.getElementById(id);const pad=n=>String(n).padStart(2,"0");
const uid=()=>"leave_"+Date.now().toString(16)+"_"+Math.random().toString(16).slice(2);
const norm=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
let leaves=[],agents=[],monthCursor=new Date(new Date().getFullYear(),new Date().getMonth(),1),user=null,docRef=null,unsub=null,hubUnsub=null,remoteApplying=false;
const parentWin=(()=>{try{return parent&&parent!==window?parent:window}catch{return window}})();
const fb=()=>{try{return parentWin.firebase||window.firebase}catch{return null}};
const hub=()=>{try{return parentWin.InovtecDataHub||null}catch{return null}};
function parse(s,fallback){try{const v=JSON.parse(s);return v??fallback}catch{return fallback}}
function loadLocal(){const x=parse(localStorage.getItem(KEY)||"[]",[]);leaves=Array.isArray(x)?x:[]}
function setLocal(){localStorage.setItem(KEY,JSON.stringify(leaves))}
function dateISO(d){return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function parseISO(s){const m=String(s||"").match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?new Date(+m[1],+m[2]-1,+m[3]):null}
function plusDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function covers(l,date){const s=parseISO(l.startDate),e=parseISO(l.endDate),d=parseISO(date);return !!(s&&e&&d&&d>=s&&d<=e&&l.status!=="rejected"&&l.status!=="cancelled")}
function approved(l){return l.status==="approved"}
function displayAgentName(a){return a?.name||a?.displayName||[a?.identity?.prenom,a?.identity?.nom].filter(Boolean).join(" ")||"Agent"}
function initials(name){return String(name||"?").split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join("")||"?"}
function leaveTone(l){if(l.status==="rejected"||l.status==="cancelled")return l.status;if(l.status==="pending")return"pending";return /maladie|absence/i.test(l.type||"")||l.sourceType==="absence"?"sick":"approved"}
function statusLabel(s){return s==="pending"?"À valider":s==="approved"?"Validée":s==="rejected"?"Refusée":"Annulée"}
function partLabel(v,edge){if(v==="morning")return edge==="start"?"matin":"jusqu’au matin";if(v==="afternoon")return edge==="start"?"après-midi":"jusqu’à l’après-midi";return"journée complète"}
function fmtDate(s){const d=parseISO(s);return d?new Intl.DateTimeFormat("fr-FR",{day:"numeric",month:"short",year:"numeric"}).format(d):"—"}
function fmtRange(l){return l.startDate===l.endDate?fmtDate(l.startDate):`${fmtDate(l.startDate)} → ${fmtDate(l.endDate)}`}
function planning(){const p=parse(localStorage.getItem(PLANNING_KEY)||"{}",{});return p&&p.weeks?p:{agents:[],weeks:{}}}
function mondayIndex(d){return(d.getDay()+6)%7}
function dateFromWeek(key,day){const m=String(key).match(/^(\d{4})-W(\d{2})$/);if(!m)return null;const year=+m[1],week=+m[2],jan4=new Date(year,0,4),offset=(jan4.getDay()+6)%7,mon=new Date(year,0,4-offset);mon.setDate(mon.getDate()+(week-1)*7+(Number(day)||0));return mon}
function planningAgentId(l,p){const byRef=(p.agents||[]).find(a=>String(a.refId||a.id)===String(l.agentRefId));if(byRef)return byRef.id;const n=norm(l.agentName);return(p.agents||[]).find(a=>norm(a.name)===n)?.id||""}
function coverage(l){if(!approved(l))return{total:0,replaced:0,pending:0};const p=planning(),orig=planningAgentId(l,p);if(!orig)return{total:0,replaced:0,pending:0};let pending=0,replaced=0;Object.entries(p.weeks||{}).forEach(([w,rows])=>(rows||[]).forEach(e=>{if(e?._replacementFor?.leaveId===l.id)replaced++;else if(String(e.agentId)===String(orig)){const d=dateFromWeek(w,e.day);if(d&&covers(l,dateISO(d)))pending++}}));return{total:pending+replaced,replaced,pending}}
function updateKPIs(){const today=dateISO(new Date()),now=parseISO(today);$("kpiToday").textContent=leaves.filter(l=>approved(l)&&covers(l,today)).length;$("kpiPending").textContent=leaves.filter(l=>l.status==="pending").length;$("kpiUpcoming").textContent=leaves.filter(l=>approved(l)&&parseISO(l.startDate)>now).length;$("kpiCoverage").textContent=leaves.reduce((n,l)=>n+coverage(l).pending,0)}
function buildAgentSelect(){const sel=$("agentSelect"),value=sel.value;sel.innerHTML='<option value="">Choisir un agent…</option>';agents.forEach(a=>{const o=document.createElement("option");o.value=a.id;o.textContent=displayAgentName(a);sel.appendChild(o)});if([...sel.options].some(o=>o.value===value))sel.value=value}
function renderTimeline(){const days=new Date(monthCursor.getFullYear(),monthCursor.getMonth()+1,0).getDate(),start=dateISO(monthCursor),end=dateISO(new Date(monthCursor.getFullYear(),monthCursor.getMonth(),days));$("monthLabel").textContent=new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric"}).format(monthCursor).replace(/^./,c=>c.toUpperCase());const visibleAgents=agents.filter(a=>leaves.some(l=>String(l.agentRefId)===String(a.id)&&l.startDate<=end&&l.endDate>=start));const allAgents=visibleAgents.length?visibleAgents:agents.slice(0,20);const wrap=$("timelineWrap");if(!allAgents.length){wrap.innerHTML='<div class="empty">Chargement des agents du Classeur Agents…</div>';return}const root=document.createElement("div");root.className="timeline";root.style.setProperty("--days",days);const head=document.createElement("div");head.className="timeline-head";head.innerHTML='<div class="timeline-agent-head">Agents</div>';for(let day=1;day<=days;day++){const d=new Date(monthCursor.getFullYear(),monthCursor.getMonth(),day),c=document.createElement("div");c.className="day-h";c.innerHTML=`<span>${new Intl.DateTimeFormat("fr-FR",{weekday:"short"}).format(d).replace(".","")}</span><strong>${day}</strong>`;head.appendChild(c)}root.appendChild(head);allAgents.forEach(a=>{const row=document.createElement("div");row.className="timeline-row";const ac=document.createElement("div");ac.className="timeline-agent";const name=displayAgentName(a),own=leaves.filter(l=>String(l.agentRefId)===String(a.id)&&l.startDate<=end&&l.endDate>=start);ac.innerHTML=`<div class="agent-avatar">${initials(name)}</div><div class="agent-copy"><strong></strong><small>${own.length?own.length+" période"+(own.length>1?"s":""):"Disponible"}</small></div>`;ac.querySelector("strong").textContent=name;row.appendChild(ac);for(let day=1;day<=days;day++){const d=new Date(monthCursor.getFullYear(),monthCursor.getMonth(),day),cell=document.createElement("div");cell.className="day-cell"+([0,6].includes(d.getDay())?" weekend":"")+(dateISO(d)===dateISO(new Date())?" today":"");row.appendChild(cell)}own.forEach(l=>{const s=Math.max(1,parseISO(l.startDate).getMonth()===monthCursor.getMonth()?parseISO(l.startDate).getDate():1),e=Math.min(days,parseISO(l.endDate).getMonth()===monthCursor.getMonth()?parseISO(l.endDate).getDate():days),band=document.createElement("button");band.type="button";band.className="leave-band "+leaveTone(l);band.style.gridColumn=`${s+1} / ${e+2}`;band.style.gridRow="1";band.style.margin="9px 3px";band.style.position="relative";band.textContent=`${l.type} · ${statusLabel(l.status)}`;band.title=`${name} — ${fmtRange(l)}`;band.onclick=()=>openEdit(l.id);row.appendChild(band)});root.appendChild(row)});wrap.innerHTML="";wrap.appendChild(root)}
function renderList(){const q=norm($("searchLeave").value),status=$("statusFilter").value,box=$("leaveList");const list=leaves.filter(l=>(status==="all"||l.status===status)&&(!q||norm(l.agentName).includes(q)||norm(l.type).includes(q))).sort((a,b)=>String(b.startDate).localeCompare(String(a.startDate)));box.innerHTML="";if(!list.length){box.innerHTML='<div class="empty">Aucune demande ou absence pour ce filtre.</div>';return}list.forEach(l=>{const cov=coverage(l),row=document.createElement("div");row.className="leave-row";const pct=cov.total?Math.round(cov.replaced/cov.total*100):0;row.innerHTML=`<div class="leave-person"><div class="agent-avatar">${initials(l.agentName)}</div><div><strong></strong><small>${l.sourceType==="request"?"Demande":"Absence enregistrée"}</small></div></div><div class="leave-meta"><b>${l.type}</b><small>${fmtRange(l)}</small></div><div><span class="status-pill ${l.status}">${statusLabel(l.status)}</span><small style="display:block;color:#7c8982;font-size:9px;margin-top:4px">Début : ${partLabel(l.startPart,"start")}</small></div><div class="coverage"><b>${approved(l)?`${cov.replaced} remplacée${cov.replaced>1?"s":""} · ${cov.pending} à couvrir`:"Remplacement après validation"}</b><div class="progress"><span style="width:${pct}%"></span></div><small>${cov.total?cov.total+" intervention"+(cov.total>1?"s":"")+" concernée"+(cov.total>1?"s":""):"Aucune intervention détectée"}</small></div><div class="row-actions"></div>`;row.querySelector(".leave-person strong").textContent=l.agentName;const actions=row.querySelector(".row-actions");if(l.status==="pending"){const ok=document.createElement("button");ok.className="mini-btn approve";ok.textContent="Valider";ok.onclick=()=>setStatus(l.id,"approved");const no=document.createElement("button");no.className="mini-btn reject";no.textContent="Refuser";no.onclick=()=>setStatus(l.id,"rejected");actions.append(ok,no)}else if(l.status==="approved"){const cancel=document.createElement("button");cancel.className="mini-btn reject";cancel.textContent="Annuler";cancel.onclick=()=>setStatus(l.id,"cancelled");actions.appendChild(cancel)}const edit=document.createElement("button");edit.className="mini-btn";edit.textContent="Modifier";edit.onclick=()=>openEdit(l.id);actions.appendChild(edit);if(approved(l)&&cov.pending){const repl=document.createElement("button");repl.className="mini-btn approve";repl.textContent="Organiser";repl.onclick=()=>{try{parentWin.location.href=`inovtec-page-shell.html?mode=planning&page=PLANNINGS-LEGACY.html%3Fv%3D20260815-menu1&replacementAgent=${encodeURIComponent(l.agentRefId)}`}catch{location.href="PLANNINGS.html"}};actions.appendChild(repl)}box.appendChild(row)})}
function render(){updateKPIs();renderTimeline();renderList();buildAgentSelect()}
function openModal(l=null){$("leaveModal").classList.add("open");$("leaveModal").setAttribute("aria-hidden","false");$("modalTitle").textContent=l?"Modifier la demande / absence":"Nouvelle demande / absence";$("leaveId").value=l?.id||"";$("agentSelect").value=l?.agentRefId||"";$("sourceType").value=l?.sourceType||"request";$("leaveType").value=l?.type||"Congés payés";$("startDate").value=l?.startDate||dateISO(new Date());$("endDate").value=l?.endDate||dateISO(new Date());$("startPart").value=l?.startPart||"full";$("endPart").value=l?.endPart||"full";$("leaveComment").value=l?.comment||"";$("deleteLeave").hidden=!l;updateStatusHint();setTimeout(()=>$("agentSelect").focus(),20)}
function closeModal(){$("leaveModal").classList.remove("open");$("leaveModal").setAttribute("aria-hidden","true")}
function openEdit(id){const l=leaves.find(x=>x.id===id);if(l)openModal(l)}
function updateStatusHint(){const absence=$("sourceType").value==="absence";$("statusHint").textContent=absence?"Une absence enregistrée est considérée comme validée immédiatement et peut déclencher les remplacements.":"Une demande de congé sera enregistrée « À valider » avant d’impacter le planning."}
async function push(reason){setLocal();render();if(!docRef||!user)return;const payload=JSON.stringify(leaves),now=Date.now();try{await docRef.set({moduleSyncV1:{conges:{payload,updatedAtMs:now,client:"conges_"+user.uid.slice(0,6),reason,version:1}}},{merge:true})}catch(e){console.warn("Congés Firebase",e)}}
function mergeRemote(remote){if(!Array.isArray(remote))return;leaves=remote;remoteApplying=true;setLocal();remoteApplying=false;render()}
function setStatus(id,status){const l=leaves.find(x=>x.id===id);if(!l)return;l.status=status;l.updatedAt=new Date().toISOString();push("status-"+status)}
function deleteCurrent(){const id=$("leaveId").value;if(!id)return;if(!confirm("Supprimer cette demande / absence ?"))return;leaves=leaves.filter(x=>x.id!==id);closeModal();push("delete")}
function onSubmit(e){e.preventDefault();const id=$("leaveId").value||uid(),ref=$("agentSelect").value,a=agents.find(x=>String(x.id)===String(ref));if(!a)return alert("Choisissez un agent.");const start=$("startDate").value,end=$("endDate").value;if(!start||!end||end<start)return alert("Vérifiez les dates de début et de fin.");const existing=leaves.find(x=>x.id===id),sourceType=$("sourceType").value,status=existing?.status||(sourceType==="absence"?"approved":"pending");const record={id,agentRefId:ref,agentName:displayAgentName(a),sourceType,type:$("leaveType").value,startDate:start,endDate:end,startPart:$("startPart").value,endPart:$("endPart").value,comment:$("leaveComment").value.trim(),status:sourceType==="absence"&&status==="pending"?"approved":status,createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(existing)Object.assign(existing,record);else leaves.push(record);closeModal();push(existing?"edit":"create")}
function bindHub(){const h=hub();if(!h){setTimeout(bindHub,250);return}agents=Array.from(h.agents||[]);buildAgentSelect();render();hubUnsub=h.subscribe(detail=>{agents=Array.from(detail.agents||[]);render()})}
function bindFirebase(){const f=fb();if(!f){console.warn("Firebase indisponible");return}f.auth().onAuthStateChanged(u=>{user=u||null;if(unsub){try{unsub()}catch{}unsub=null}if(!user){docRef=null;$("loginModal").classList.add("open");return}$("loginModal").classList.remove("open");docRef=f.firestore().collection("kanban").doc(user.uid);unsub=docRef.onSnapshot(s=>{const entry=s.exists?s.data()?.moduleSyncV1?.conges:null;if(!entry){if(leaves.length)push("migration");return}const remote=parse(entry.payload||"[]",[]);mergeRemote(remote)},e=>console.warn("Congés lecture",e))})}
function bind(){loadLocal();render();bindHub();bindFirebase();$("prevMonth").onclick=()=>{monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()-1,1);renderTimeline()};$("nextMonth").onclick=()=>{monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()+1,1);renderTimeline()};$("monthLabel").onclick=()=>{monthCursor=new Date(new Date().getFullYear(),new Date().getMonth(),1);renderTimeline()};$("newLeave").onclick=()=>openModal();$("closeModal").onclick=closeModal;$("cancelModal").onclick=closeModal;$("deleteLeave").onclick=deleteCurrent;$("leaveForm").onsubmit=onSubmit;$("sourceType").onchange=updateStatusHint;$("searchLeave").oninput=renderList;$("statusFilter").onchange=renderList;$("leaveModal").addEventListener("click",e=>{if(e.target===$("leaveModal"))closeModal()});$("loginForm").onsubmit=async e=>{e.preventDefault();const f=fb(),err=$("loginError");err.textContent="";try{await f.auth().setPersistence(f.auth.Auth.Persistence.LOCAL);await f.auth().signInWithEmailAndPassword($("loginEmail").value.trim(),$("loginPassword").value)}catch(ex){err.textContent="Connexion impossible : "+(ex?.message||"vérifiez vos identifiants.")}}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind);else bind();
})();
