(function(){
"use strict";
const $=id=>document.getElementById(id);
const VERSION=9,MAX_PHOTOS=10,MAX_PHOTO_SIZE=20*1024*1024,PHOTO_MAX_DIM=1600,PHOTO_QUALITY=.78,CHUNK_SIZE=220000,FIREBASE_TIMEOUT=12000;
let auth=null,db=null,storage=null,currentUser=null,unsubscribe=null,activeBackend=null;
let records=[],editingId=null,existingPhotos=[],pendingPhotos=[],removedPhotos=[];
const photoSourceCache=new Map();
const LEGACY_KEYS=["inovtec_discipline_cache_v8","inovtec_discipline_cloud_cache_v5","inovtec_discipline_v2","discipline"];

function nowIso(){return new Date().toISOString();}
function today(){return nowIso().slice(0,10);}
function text(v){return v==null?"":String(v);}
function newId(){return "disc_"+Date.now()+"_"+Math.random().toString(16).slice(2);}
function newPhotoId(){return "p_"+Date.now()+"_"+Math.random().toString(36).slice(2,10);}
function safeFileName(name){return text(name||"photo").replace(/[\\/:*?"<>|]+/g,"_").replace(/\s+/g,"_").slice(-120)||"photo";}
function setStatus(label,type=""){const el=$("syncStatus");if(!el)return;el.textContent=label;el.className="status"+(type?" "+type:"");}
function showNotice(message,type="warning"){const el=$("saveNotice");if(!message){el.className="hidden";el.textContent="";return;}el.className="notice "+type;el.textContent=message;}
function formatSize(n){n=Number(n)||0;if(n<1024)return n+" o";if(n<1024*1024)return Math.round(n/1024)+" Ko";return(n/1024/1024).toFixed(1)+" Mo";}
function withTimeout(promise,ms,label){return new Promise((resolve,reject)=>{let done=false;const t=setTimeout(()=>{if(done)return;done=true;reject(new Error(label||"Délai dépassé"));},ms);Promise.resolve(promise).then(v=>{if(done)return;done=true;clearTimeout(t);resolve(v);},e=>{if(done)return;done=true;clearTimeout(t);reject(e);});});}

function normalizePhoto(p){if(!p||typeof p!=="object")return null;return{name:text(p.name||"Photo"),type:text(p.type||p.mime||"image/jpeg"),size:Number(p.size)||0,path:text(p.path||""),url:text(p.url||""),backend:text(p.backend||((p.chunkIds&&p.chunkIds.length)?"firestoreChunks":"storage")),photoId:text(p.photoId||""),chunkIds:Array.isArray(p.chunkIds)?p.chunkIds.map(String):[],uploadedAt:text(p.uploadedAt||"")};}
function normalizeRecord(item,index){if(!item||typeof item!=="object")return null;const created=text(item.createdAt||item.updatedAt||nowIso());const r={id:text(item.id||("legacy_"+(index||0)+"_"+Date.now())),agent:text(item.agent||"").trim(),site:text(item.site||"").trim(),date:text(item.date||"").trim(),niveau:text(item.niveau||item.level||"Observation").trim()||"Observation",statut:text(item.statut||"Ouvert").trim()||"Ouvert",responsable:text(item.responsable||item.resp||"").trim(),motif:text(item.motif||item.reason||"").trim(),temoins:text(item.temoins||item.tem||"").trim(),description:text(item.description||item.desc||"").trim(),suite:text(item.suite||"").trim(),photos:Array.isArray(item.photos)?item.photos.map(normalizePhoto).filter(Boolean):[],createdAt:created,updatedAt:text(item.updatedAt||created),createdBy:text(item.createdBy||""),updatedBy:text(item.updatedBy||"")};if(!r.agent&&!r.motif&&!r.description)return null;return r;}
function normalizeList(list){return Array.isArray(list)?list.map(normalizeRecord).filter(Boolean):[];}
function legacyPrimary(data){const out=[];data=data||{};if(data.recordsById&&typeof data.recordsById==="object")Object.keys(data.recordsById).forEach(k=>{const r=normalizeRecord(data.recordsById[k],out.length);if(r){if(!r.id)r.id=k;out.push(r);}});if(Array.isArray(data.records))data.records.forEach((item,i)=>{const r=normalizeRecord(item,i);if(r&&!out.some(x=>x.id===r.id))out.push(r);});return out;}
function primaryRecords(data){if(Array.isArray(data&&data.recordsV9))return normalizeList(data.recordsV9);if(Array.isArray(data&&data.recordsV8))return normalizeList(data.recordsV8);if(Array.isArray(data&&data.recordsV7))return normalizeList(data.recordsV7);return legacyPrimary(data);}
function fallbackRecords(data){if(Array.isArray(data&&data.disciplineRecordsV9))return normalizeList(data.disciplineRecordsV9);if(Array.isArray(data&&data.disciplineRecordsV8))return normalizeList(data.disciplineRecordsV8);if(Array.isArray(data&&data.disciplineRecordsV7))return normalizeList(data.disciplineRecordsV7);return [];}
function stampOf(data,isoKey,serverKey){if(data&&data[isoKey]){const t=Date.parse(data[isoKey]);if(Number.isFinite(t))return t;}const v=data&&data[serverKey];if(v&&typeof v.toMillis==="function")return v.toMillis();return 0;}
function pendingKey(){return currentUser?"inovtec_discipline_pending_v9_"+currentUser.uid:"inovtec_discipline_pending_v9";}
function cacheKey(){return currentUser?"inovtec_discipline_cache_v9_"+currentUser.uid:"inovtec_discipline_cache_v9";}
function saveCache(list){try{localStorage.setItem(cacheKey(),JSON.stringify({records:list,updatedAtIso:nowIso()}));}catch(e){console.warn(e);}}
function savePending(list){try{localStorage.setItem(pendingKey(),JSON.stringify({records:list,updatedAtIso:nowIso()}));}catch(e){console.warn(e);}}
function readPending(){try{const x=JSON.parse(localStorage.getItem(pendingKey())||"null");return x&&Array.isArray(x.records)?{records:normalizeList(x.records),stamp:Date.parse(x.updatedAtIso)||0}:null;}catch(e){return null;}}
function clearPending(){try{localStorage.removeItem(pendingKey());}catch(e){}}
function loadLocalBest(){let best={records:[],stamp:0};try{const c=JSON.parse(localStorage.getItem(cacheKey())||"null");if(c&&Array.isArray(c.records))best={records:normalizeList(c.records),stamp:Date.parse(c.updatedAtIso)||0};}catch(e){}LEGACY_KEYS.forEach(key=>{try{const raw=JSON.parse(localStorage.getItem(key)||"null");let list=[];if(Array.isArray(raw))list=normalizeList(raw);else if(raw&&Array.isArray(raw.records))list=normalizeList(raw.records);if(list.length>best.records.length)best={records:list,stamp:best.stamp};}catch(e){}});return best;}

function primaryRef(){return db.collection("discipline").doc(currentUser.uid);}
function fallbackRef(){return db.collection("kanban").doc(currentUser.uid);}
async function safeGet(ref){try{return{ok:true,snap:await withTimeout(ref.get(),8000,"Lecture Firebase trop longue")};}catch(error){console.warn("Lecture Firebase",error);return{ok:false,error};}}
function chooseCloud(primary,fallback){const pData=primary.ok&&primary.snap.exists?(primary.snap.data()||{}):{},fData=fallback.ok&&fallback.snap.exists?(fallback.snap.data()||{}):{};const p={name:"primary",ref:primaryRef(),records:primaryRecords(pData),stamp:stampOf(pData,"disciplineUpdatedAtIso","updatedAt"),readable:primary.ok};const f={name:"fallback",ref:fallbackRef(),records:fallbackRecords(fData),stamp:stampOf(fData,"disciplineUpdatedAtIso","disciplineUpdatedAt"),readable:fallback.ok};if(f.records.length&&(!p.records.length||f.stamp>p.stamp))return f;if(p.readable)return p;if(f.readable)return f;return null;}
async function refreshCloud(){if(!currentUser)return;setStatus("Synchronisation…");const results=await Promise.all([safeGet(primaryRef()),safeGet(fallbackRef())]),chosen=chooseCloud(results[0],results[1]),local=loadLocalBest(),pending=readPending();if(chosen){activeBackend=chosen;records=chosen.records;const cloudStamp=chosen.stamp||0;if(local.records.length&&!records.length)records=local.records;if(pending&&pending.stamp>=cloudStamp){records=pending.records;saveCache(records);render();setStatus("Synchronisation en attente","warning");await flushPending();return;}saveCache(records);render();startListener(chosen);setStatus("Synchronisé • "+records.length+" dossier"+(records.length>1?"s":""),"ok");}else{activeBackend=null;records=(pending&&pending.records)||local.records;saveCache(records);render();setStatus("Mode local • synchronisation en attente","warning");}}
function startListener(backend){if(unsubscribe){unsubscribe();unsubscribe=null;}if(!backend||!backend.ref)return;unsubscribe=backend.ref.onSnapshot(snap=>{const data=snap.exists?(snap.data()||{}):{},incoming=backend.name==="primary"?primaryRecords(data):fallbackRecords(data),cloudStamp=backend.name==="primary"?stampOf(data,"disciplineUpdatedAtIso","updatedAt"):stampOf(data,"disciplineUpdatedAtIso","disciplineUpdatedAt"),pending=readPending();if(pending&&pending.stamp>cloudStamp){records=pending.records;saveCache(records);render();setStatus("Synchronisation en attente","warning");return;}records=incoming;saveCache(records);render();setStatus("Synchronisé • "+records.length+" dossier"+(records.length>1?"s":""),"ok");},error=>{console.warn("Ecoute Firebase",error);setStatus("Connexion interrompue • données conservées","warning");});}
async function writePrimary(list,stamp){await withTimeout(primaryRef().set({recordsV9:list,disciplineUpdatedAtIso:stamp,storageVersion:VERSION,ownerUid:currentUser.uid,ownerEmail:currentUser.email||"",updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true}),FIREBASE_TIMEOUT,"Firebase principal trop lent");return{name:"primary",ref:primaryRef()};}
async function writeFallback(list,stamp){await withTimeout(fallbackRef().set({disciplineRecordsV9:list,disciplineUpdatedAtIso:stamp,disciplineStorageVersion:VERSION,disciplineUpdatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true}),FIREBASE_TIMEOUT,"Firebase de secours trop lent");return{name:"fallback",ref:fallbackRef()};}
async function saveAll(list){const stamp=nowIso();let firstError=null;records=list;saveCache(records);savePending(list);render();try{const b=await writePrimary(list,stamp);clearPending();activeBackend=b;startListener(b);return{synced:true,backend:"primary"};}catch(error){firstError=error;console.warn("Ecriture Discipline principale",error);}try{const f=await writeFallback(list,stamp);clearPending();activeBackend=f;startListener(f);return{synced:true,backend:"fallback",recovered:true};}catch(error2){console.warn("Ecriture Firebase de secours",error2);return{synced:false,error:firstError||error2};}}
async function flushPending(){const pending=readPending();if(!pending||!currentUser)return true;const result=await saveAll(pending.records);if(result.synced){setStatus("Synchronisé • "+records.length+" dossier"+(records.length>1?"s":""),"ok");return true;}setStatus("Enregistré sur cet appareil • synchronisation en attente","warning");return false;}

function slugLevel(level){if(level==="Observation")return"observation";if(level==="Avertissement")return"avertissement";if(level==="Mise en demeure")return"mise-en-demeure";return"licenciement";}
function clearPendingPreviews(){pendingPhotos.forEach(p=>{if(p.previewUrl)URL.revokeObjectURL(p.previewUrl);});pendingPhotos=[];if($("photos"))$("photos").value="";}
function resetForm(){editingId=null;$("recordForm").reset();clearPendingPreviews();existingPhotos=[];removedPhotos=[];$("date").value=today();$("niveau").value="Observation";$("statut").value="Ouvert";$("formTitle").textContent="Nouveau dossier";$("submitLabel").textContent="Enregistrer";$("cancelEditBtn").classList.add("hidden");$("saveBtn").disabled=false;renderPhotoPreview();}
function photoCacheKey(photo){return photo.photoId||photo.url||photo.path||photo.chunkIds.join("|");}
async function resolvePhotoSource(photo){photo=normalizePhoto(photo);if(!photo)throw new Error("Photo invalide");const key=photoCacheKey(photo);if(photoSourceCache.has(key))return photoSourceCache.get(key);if(photo.url){photoSourceCache.set(key,photo.url);return photo.url;}if(photo.backend!=="firestoreChunks"||!photo.chunkIds.length)throw new Error("Photo introuvable");const snaps=await Promise.all(photo.chunkIds.map(id=>withTimeout(db.collection("chantiers").doc(id).get(),9000,"Chargement photo trop long")));const parts=snaps.map(snap=>{if(!snap.exists)throw new Error("Morceau de photo manquant");const d=snap.data()||{};if(d._type!=="disciplinePhotoChunk"||d.ownerUid!==currentUser.uid)throw new Error("Photo non autorisée");return{index:Number(d.chunkIndex)||0,data:text(d.data)};}).sort((a,b)=>a.index-b.index);const src=parts.map(p=>p.data).join("");if(src.indexOf("data:image/")!==0)throw new Error("Photo corrompue");photoSourceCache.set(key,src);return src;}
function renderStoredPhoto(photo,index){const wrap=$("photoPreview"),card=document.createElement("div");card.className="photo-item";const holder=document.createElement("div");holder.className="photo-loading";holder.textContent="Chargement de la photo…";const name=document.createElement("div");name.className="photo-name";name.textContent=photo.name||("Photo "+(index+1));const meta=document.createElement("div");meta.className="photo-meta";meta.textContent=photo.size?formatSize(photo.size):"Photo enregistrée";const remove=document.createElement("button");remove.type="button";remove.className="photo-remove";remove.textContent="×";remove.setAttribute("aria-label","Retirer la photo");remove.addEventListener("click",()=>{const old=existingPhotos.splice(index,1)[0];if(old)removedPhotos.push(old);renderPhotoPreview();});card.append(holder,remove,name,meta);wrap.appendChild(card);resolvePhotoSource(photo).then(src=>{if(!card.isConnected)return;const img=document.createElement("img");img.alt=photo.name||("Photo "+(index+1));img.src=src;holder.replaceWith(img);}).catch(()=>{holder.textContent="Photo momentanément indisponible";});}
function renderPhotoPreview(){const wrap=$("photoPreview");if(!wrap)return;wrap.innerHTML="";const total=existingPhotos.length+pendingPhotos.length;$("photoHelp").textContent=total+"/"+MAX_PHOTOS+" photo"+(total>1?"s":"")+" — les nouvelles photos sont enregistrées dans Firebase avec le dossier.";existingPhotos.forEach(renderStoredPhoto);pendingPhotos.forEach((photo,index)=>{const card=document.createElement("div");card.className="photo-item";const img=document.createElement("img");img.src=photo.previewUrl;img.alt=photo.file.name||("Nouvelle photo "+(index+1));const name=document.createElement("div");name.className="photo-name";name.textContent=photo.file.name||("Nouvelle photo "+(index+1));const meta=document.createElement("div");meta.className="photo-meta";meta.textContent=formatSize(photo.file.size)+" • à enregistrer";const remove=document.createElement("button");remove.type="button";remove.className="photo-remove";remove.textContent="×";remove.setAttribute("aria-label","Retirer la photo");remove.addEventListener("click",()=>{const old=pendingPhotos.splice(index,1)[0];if(old&&old.previewUrl)URL.revokeObjectURL(old.previewUrl);renderPhotoPreview();});card.append(img,remove,name,meta);wrap.appendChild(card);});}
function editRecord(id){const r=records.find(x=>x.id===id);if(!r)return;clearPendingPreviews();editingId=id;removedPhotos=[];["agent","site","date","niveau","statut","responsable","motif","temoins","description","suite"].forEach(field=>{$(field).value=r[field]||"";});existingPhotos=(r.photos||[]).map(p=>Object.assign({},p));renderPhotoPreview();$("formTitle").textContent="Consulter / modifier le dossier";$("submitLabel").textContent="Enregistrer les modifications";$("cancelEditBtn").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"});}

function fileToImage(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img);};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("Image illisible"));};img.src=url;});}
async function preparePhotoDataUrl(file){const img=await withTimeout(fileToImage(file),10000,"Lecture de la photo trop longue");const w=img.naturalWidth||img.width||1,h=img.naturalHeight||img.height||1,scale=Math.min(1,PHOTO_MAX_DIM/Math.max(w,h));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(w*scale));canvas.height=Math.max(1,Math.round(h*scale));const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Préparation photo impossible");ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL("image/jpeg",PHOTO_QUALITY);}
function chunkIdsFor(recordId,pid,count){const shortUid=currentUser.uid.replace(/[^a-zA-Z0-9]/g,"").slice(0,12),safeRecord=recordId.replace(/[^a-zA-Z0-9_-]/g,"_").slice(0,80),ids=[];for(let i=0;i<count;i++)ids.push("__discipline_photo__"+shortUid+"_"+safeRecord+"_"+pid+"_"+String(i).padStart(3,"0"));return ids;}
async function commitChunkGroup(group){const batch=db.batch();group.forEach(item=>batch.set(db.collection("chantiers").doc(item.id),item.data));await withTimeout(batch.commit(),FIREBASE_TIMEOUT,"Enregistrement photo trop long");}
async function storePhotoInFirestore(recordId,file,position,total){setStatus("Préparation photo "+position+"/"+total+"…");const dataUrl=await preparePhotoDataUrl(file),chunks=[];for(let i=0;i<dataUrl.length;i+=CHUNK_SIZE)chunks.push(dataUrl.slice(i,i+CHUNK_SIZE));if(!chunks.length)throw new Error("Photo vide");const pid=newPhotoId(),ids=chunkIdsFor(recordId,pid,chunks.length),created=nowIso(),items=chunks.map((chunk,index)=>({id:ids[index],data:{_type:"disciplinePhotoChunk",_hidden:true,ownerUid:currentUser.uid,recordId,photoId:pid,chunkIndex:index,totalChunks:chunks.length,data:chunk,name:file.name||"Photo",mime:"image/jpeg",originalSize:file.size||0,createdAtIso:created}}));for(let start=0;start<items.length;start+=8){const pct=Math.min(100,Math.round((start+Math.min(8,items.length-start))/items.length*100));setStatus("Enregistrement photo "+position+"/"+total+"… "+pct+"%");await commitChunkGroup(items.slice(start,start+8));}const meta={name:file.name||"Photo",type:"image/jpeg",size:file.size||0,backend:"firestoreChunks",photoId:pid,chunkIds:ids,uploadedAt:created};photoSourceCache.set(pid,dataUrl);return meta;}
async function deletePhotoAsset(photo){photo=normalizePhoto(photo);if(!photo)return;if(photo.backend==="firestoreChunks"&&photo.chunkIds.length){for(let start=0;start<photo.chunkIds.length;start+=20){const batch=db.batch();photo.chunkIds.slice(start,start+20).forEach(id=>batch.delete(db.collection("chantiers").doc(id)));try{await batch.commit();}catch(e){console.warn("Suppression photo Firestore",e);}}photoSourceCache.delete(photoCacheKey(photo));return;}if(storage&&photo.path){try{await storage.ref().child(photo.path).delete();}catch(e){console.warn("Suppression ancienne photo Storage",e);}}}
async function rollbackPhotos(list){for(const photo of list)await deletePhotoAsset(photo);}

function filtered(){const q=$("search").value.trim().toLowerCase(),status=$("statusFilter").value,level=$("levelFilter").value;return records.slice().filter(r=>{const hay=[r.agent,r.site,r.motif,r.description,r.responsable].join(" ").toLowerCase();return(!q||hay.includes(q))&&(!status||r.statut===status)&&(!level||r.niveau===level);}).sort((a,b)=>text(b.date).localeCompare(text(a.date))||text(b.updatedAt).localeCompare(text(a.updatedAt)));}
function button(label,fn,className=""){const b=document.createElement("button");b.type="button";b.textContent=label;b.className="btn btn-secondary"+(className?" "+className:"");b.style.padding="6px 8px";b.style.fontSize="11px";b.addEventListener("click",fn);return b;}
function render(){const list=filtered();$("count").textContent=String(list.length);const wrap=$("recordsWrap");wrap.innerHTML="";if(!list.length){const empty=document.createElement("div");empty.className="empty";empty.textContent="Aucun dossier.";wrap.appendChild(empty);return;}const table=document.createElement("table"),thead=document.createElement("thead"),trh=document.createElement("tr");["Date","Agent","Site","Niveau","Statut","Motif","Photos","Actions"].forEach(label=>{const th=document.createElement("th");th.textContent=label;trh.appendChild(th);});thead.appendChild(trh);table.appendChild(thead);const tbody=document.createElement("tbody");list.forEach(r=>{const tr=document.createElement("tr");[r.date||"—",r.agent||"—",r.site||"—"].forEach(v=>{const td=document.createElement("td");td.textContent=v;tr.appendChild(td);});const tdLevel=document.createElement("td"),badge=document.createElement("span");badge.className="level "+slugLevel(r.niveau);badge.textContent=r.niveau||"—";tdLevel.appendChild(badge);tr.appendChild(tdLevel);const tdStatus=document.createElement("td");tdStatus.textContent=r.statut||"—";tr.appendChild(tdStatus);const tdMotif=document.createElement("td");tdMotif.textContent=r.motif||"—";tr.appendChild(tdMotif);const tdPhotos=document.createElement("td"),count=document.createElement("span");count.className="photo-count";count.textContent=String((r.photos||[]).length);tdPhotos.appendChild(count);tr.appendChild(tdPhotos);const tdActions=document.createElement("td"),actions=document.createElement("div");actions.className="actions";actions.append(button("Générer PDF",()=>generatePdf(r.id)),button("Consulter / Modifier",()=>editRecord(r.id)),button("Supprimer",()=>deleteRecord(r.id),"btn-danger"));tdActions.appendChild(actions);tr.appendChild(tdActions);tbody.appendChild(tr);});table.appendChild(tbody);wrap.appendChild(table);}
async function deleteRecord(id){const r=records.find(x=>x.id===id);if(!r||!confirm("Supprimer définitivement le dossier de "+r.agent+" ?"))return;setStatus("Suppression…");const next=records.filter(x=>x.id!==id),result=await saveAll(next);if(result.synced){for(const photo of(r.photos||[]))await deletePhotoAsset(photo);showNotice("Dossier supprimé.","success");}else showNotice("Suppression conservée sur cet appareil. La synchronisation se fera automatiquement.","warning");if(editingId===id)resetForm();render();}

function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error("Image inaccessible"));img.src=src;});}
async function imageForPdf(photo){const src=await resolvePhotoSource(photo);let objectUrl="",img;if(/^data:image\//.test(src)){img=await loadImage(src);}else{const response=await fetch(src);if(!response.ok)throw new Error("Image indisponible");const blob=await response.blob();objectUrl=URL.createObjectURL(blob);img=await loadImage(objectUrl);}try{const ratio=Math.min(1,1600/Math.max(img.naturalWidth||1,img.naturalHeight||1)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round((img.naturalWidth||1)*ratio));canvas.height=Math.max(1,Math.round((img.naturalHeight||1)*ratio));const ctx=canvas.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);return{data:canvas.toDataURL("image/jpeg",.82),width:canvas.width,height:canvas.height};}finally{if(objectUrl)URL.revokeObjectURL(objectUrl);}}
async function generatePdf(id){const r=records.find(x=>x.id===id);if(!r)return;if(!window.jspdf||!window.jspdf.jsPDF){alert("Le générateur PDF n’est pas disponible. Recharge la page puis réessaie.");return;}setStatus("Génération du PDF…");try{const pdf=new window.jspdf.jsPDF({orientation:"portrait",unit:"mm",format:"a4"}),m=15,w=180,pageH=297;let y=18;function space(h){if(y+h>pageH-m){pdf.addPage();y=18;}}function line(label,value){pdf.setFontSize(10);pdf.setFont("helvetica","bold");pdf.text(label+" :",m,y);pdf.setFont("helvetica","normal");const lines=pdf.splitTextToSize(text(value)||"—",130);pdf.text(lines,60,y);y+=Math.max(6,lines.length*5);}function block(title,value){space(18);pdf.setFont("helvetica","bold");pdf.setFontSize(13);pdf.text(title,m,y);y+=7;pdf.setFont("helvetica","normal");pdf.setFontSize(10);const lines=pdf.splitTextToSize(text(value)||"—",w);lines.forEach(l=>{space(7);pdf.text(l,m,y);y+=5;});y+=4;}pdf.setFont("helvetica","bold");pdf.setFontSize(20);pdf.text("Dossier disciplinaire",m,y);y+=10;[["Agent",r.agent],["Date des faits",r.date],["Site",r.site],["Niveau",r.niveau],["Statut",r.statut],["Motif",r.motif],["Témoins",r.temoins],["Responsable",r.responsable]].forEach(v=>line(v[0],v[1]));block("Description factuelle",r.description);block("Suite donnée / prochaine action",r.suite);const photos=r.photos||[];if(photos.length){space(12);pdf.setFont("helvetica","bold");pdf.setFontSize(13);pdf.text("Photos / éléments visuels ("+photos.length+")",m,y);y+=7;for(let i=0;i<photos.length;i++){space(65);try{setStatus("Ajout photo "+(i+1)+"/"+photos.length+" au PDF…");const image=await imageForPdf(photos[i]),ratio=Math.min(w/image.width,55/image.height),iw=image.width*ratio,ih=image.height*ratio;pdf.addImage(image.data,"JPEG",m+(w-iw)/2,y,iw,ih,undefined,"FAST");y+=ih+5;}catch(e){console.warn(e);pdf.setFontSize(9);pdf.text("Photo "+(i+1)+" indisponible",m,y);y+=7;}}}pdf.save("dossier_disciplinaire_"+safeFileName(r.agent||"agent")+"_"+(r.date||today())+".pdf");setStatus("PDF généré","ok");}catch(error){console.error(error);setStatus("Erreur PDF","warning");alert("Impossible de générer le PDF.");}}
function exportJSON(){const blob=new Blob([JSON.stringify({exportedAt:nowIso(),records},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="discipline_"+today()+".json";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}

$("photos").addEventListener("change",event=>{const files=Array.from(event.target.files||[]),available=MAX_PHOTOS-existingPhotos.length-pendingPhotos.length;if(available<=0){alert("Maximum "+MAX_PHOTOS+" photos par dossier.");event.target.value="";return;}files.slice(0,available).forEach(file=>{if(text(file.type).indexOf("image/")!==0){alert(file.name+" n’est pas une image.");return;}if(file.size>MAX_PHOTO_SIZE){alert(file.name+" dépasse 20 Mo.");return;}pendingPhotos.push({file,previewUrl:URL.createObjectURL(file)});});event.target.value="";renderPhotoPreview();});
$("recordForm").addEventListener("submit",async event=>{event.preventDefault();showNotice("");if(!currentUser){alert("La session a expiré. Reconnecte-toi.");return;}const data={};["agent","site","date","niveau","statut","responsable","motif","temoins","description","suite"].forEach(field=>{data[field]=$(field).value.trim();});if(!data.agent||!data.date||!data.motif||!data.description){alert("Agent, date, motif et description sont obligatoires.");return;}const id=editingId||newId(),old=records.find(r=>r.id===id),photoItems=pendingPhotos.slice(),uploaded=[],basePhotos=existingPhotos.slice(),toRemove=removedPhotos.slice();$("saveBtn").disabled=true;$("submitLabel").textContent=photoItems.length?"Enregistrement des photos…":"Enregistrement…";try{for(let p=0;p<photoItems.length;p++)uploaded.push(await storePhotoInFirestore(id,photoItems[p].file,p+1,photoItems.length));}catch(photoError){console.error("Enregistrement photo",photoError);await rollbackPhotos(uploaded);setStatus("Photo non enregistrée","warning");showNotice("La photo n’a pas pu être enregistrée. Le dossier n’a pas été validé : tes informations restent affichées pour que tu puisses réessayer.","warning");$("saveBtn").disabled=false;$("submitLabel").textContent=editingId?"Enregistrer les modifications":"Enregistrer";return;}const record=Object.assign({},old||{},data,{id,photos:basePhotos.concat(uploaded),createdAt:(old&&old.createdAt)||nowIso(),createdBy:(old&&old.createdBy)||currentUser.uid,updatedAt:nowIso(),updatedBy:currentUser.uid}),next=records.filter(r=>r.id!==id);next.push(record);setStatus("Enregistrement du dossier…");$("submitLabel").textContent="Enregistrement du dossier…";try{const result=await saveAll(next);if(result.synced){for(const photo of toRemove)await deletePhotoAsset(photo);setStatus("Dossier et photos synchronisés","ok");showNotice("Dossier enregistré avec "+record.photos.length+" photo"+(record.photos.length>1?"s":"")+".","success");}else{setStatus("Dossier et photos enregistrés • synchronisation en attente","warning");showNotice("Le dossier et les photos sont enregistrés. La synchronisation du dossier se terminera automatiquement.","warning");}resetForm();render();}catch(error){console.error(error);setStatus("Dossier enregistré sur cet appareil","warning");showNotice("Les photos sont enregistrées et le dossier est conservé sur cet appareil. La synchronisation se fera automatiquement.","warning");resetForm();render();}});
$("cancelEditBtn").addEventListener("click",resetForm);["search","statusFilter","levelFilter"].forEach(id=>$(id).addEventListener(id==="search"?"input":"change",render));$("exportBtn").addEventListener("click",exportJSON);$("syncBtn").addEventListener("click",refreshCloud);$("logoutBtn").addEventListener("click",()=>auth.signOut());
$("loginForm").addEventListener("submit",async event=>{event.preventDefault();$("loginError").textContent="";$("loginBtn").disabled=true;$("loginBtn").textContent="Connexion…";try{try{try{await auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL)}catch(_e1){try{await auth.setPersistence(firebase.auth.Auth.Persistence.SESSION)}catch(_e2){try{await auth.setPersistence(firebase.auth.Auth.Persistence.NONE)}catch(_e3){}}}}catch(e){}await auth.signInWithEmailAndPassword($("loginEmail").value.trim(),$("loginPassword").value);}catch(error){console.error(error);$("loginError").textContent="Connexion impossible : "+(error.message||"vérifie le mot de passe.");}finally{$("loginBtn").disabled=false;$("loginBtn").textContent="Se connecter";}});

function init(){if(!window.INOVTEC_FIREBASE_CONFIG){$("loginError").textContent="Configuration Firebase introuvable.";return;}if(!window.firebase||!firebase.auth||!firebase.firestore){$("loginError").textContent="Firebase n’a pas pu se charger. Recharge la page.";return;}try{if(!firebase.apps.length)firebase.initializeApp(window.INOVTEC_FIREBASE_CONFIG);auth=firebase.auth();db=firebase.firestore();try{storage=typeof firebase.storage==="function"?firebase.storage():null;}catch(e){storage=null;}}catch(error){console.error(error);$("loginError").textContent="Impossible de démarrer Firebase.";return;}auth.onAuthStateChanged(async user=>{if(!user){currentUser=null;activeBackend=null;if(unsubscribe){unsubscribe();unsubscribe=null;}$("app").classList.add("hidden");$("loginScreen").classList.remove("hidden");return;}currentUser=user;$("loginScreen").classList.add("hidden");$("app").classList.remove("hidden");await refreshCloud();});window.addEventListener("online",()=>{if(currentUser)flushPending().then(refreshCloud);});window.addEventListener("offline",()=>setStatus("Hors ligne • données conservées","warning"));window.addEventListener("focus",()=>{if(currentUser)refreshCloud();});document.addEventListener("visibilitychange",()=>{if(!document.hidden&&currentUser)refreshCloud();});setInterval(()=>{if(currentUser&&navigator.onLine)flushPending();},30000);resetForm();}
init();
})();