(()=>{
"use strict";
const KEY="inovtec_plannings_v2";
const DAYS=["Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi","Dimanche"];
const MONTHS=["janvier","février","mars","avril","mai","juin","juillet","août","septembre","octobre","novembre","décembre"];
const START_HOUR=6,END_HOUR=22;
const $=id=>document.getElementById(id);
const pad=n=>String(n).padStart(2,"0");
const norm=v=>String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
function addDays(d,n){const x=new Date(d.getFullYear(),d.getMonth(),d.getDate());x.setDate(x.getDate()+n);return x}
function mondayIndex(d){return(d.getDay()+6)%7}
function dateFromWeek(key,day=0){const m=String(key||"").match(/^(\d{4})-W(\d{2})$/);if(!m)return null;const year=+m[1],week=+m[2],jan4=new Date(year,0,4),mon=addDays(jan4,-mondayIndex(jan4));return addDays(mon,(week-1)*7+day)}
function rangeLabel(a,b){if(!a||!b)return"Semaine affichée";if(a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth())return`${a.getDate()}-${b.getDate()} ${MONTHS[b.getMonth()]} ${b.getFullYear()}`;if(a.getFullYear()===b.getFullYear())return`${a.getDate()} ${MONTHS[a.getMonth()]} - ${b.getDate()} ${MONTHS[b.getMonth()]} ${b.getFullYear()}`;return`${a.getDate()} ${MONTHS[a.getMonth()]} ${a.getFullYear()} - ${b.getDate()} ${MONTHS[b.getMonth()]} ${b.getFullYear()}`}
function safeName(v){return String(v||"planning").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9_-]+/g,"_").replace(/^_+|_+$/g,"").slice(0,80)||"planning"}
function timeToMin(t){const m=String(t||"").match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):START_HOUR*60}
function loadState(){try{const s=JSON.parse(localStorage.getItem(KEY)||"{}");return s&&Array.isArray(s.agents)&&s.weeks?s:{agents:[],weeks:{},selected:null}}catch{return{agents:[],weeks:{},selected:null}}}
function hubAgents(){try{return parent?.InovtecDataHub?.readyAgents?Array.from(parent.InovtecDataHub.agents||[]):[]}catch{return[]}}
function hubName(a){return[a?.identity?.prenom,a?.identity?.nom].filter(Boolean).join(" ").trim()||a?.displayName||a?.name||"Agent sans nom"}
function copiesFor(agent){const masters=hubAgents();const m=masters.find(x=>String(x.id)===String(agent.refId||agent.id)||norm(hubName(x))===norm(agent.name));const raw=m?.job?.planningCopies;const n=Math.round(Number(raw));return Number.isFinite(n)&&n>=1?Math.min(10,n):2}
function currentWeek(){return $("week")?.value||""}
function agentData(state,week,agent){const start=dateFromWeek(week,0),end=dateFromWeek(week,6),groups=DAYS.map(()=>[]);const rows=Array.isArray(state.weeks?.[week])?state.weeks[week]:[];rows.filter(e=>String(e.agentId)===String(agent.id)).sort((a,b)=>Number(a.day)-Number(b.day)||String(a.start).localeCompare(String(b.start))).forEach(e=>{const d=Math.max(0,Math.min(6,Number(e.day)||0));groups[d].push({start:e.start||"06:00",end:e.end||"07:00",task:e.task||"Intervention",site:e.site||"",note:e.note||""})});return{agent:agent.name||"Agent",start,end,groups}}
function jsPDFClass(){return window.jspdf?.jsPDF||window.jsPDF||null}
function drawHeader(doc,data){doc.setFillColor(6,78,59);doc.roundedRect(8,7,281,23,4,4,"F");doc.setTextColor(255,255,255);doc.setFont("helvetica","bold");doc.setFontSize(7);doc.text("PLANNING HEBDOMADAIRE",15,13);doc.setFontSize(18);doc.text(String(data.agent||"Agent"),15,21,{maxWidth:190});doc.setFontSize(10);doc.text(rangeLabel(data.start,data.end),15,27);doc.setFontSize(8);doc.text("INOVTEC DASHBOARD",281,18,{align:"right"});doc.setFont("helvetica","normal");doc.setTextColor(0,0,0)}
function drawGrid(doc,data){const x=8,y=37,w=281,headH=12,timeW=14,bodyH=144,hourH=bodyH/(END_HOUR-START_HOUR),dayW=(w-timeW)/7,bodyY=y+headH;doc.setFillColor(243,247,245);doc.rect(x,y,w,headH,"F");doc.setDrawColor(178,178,178);doc.setLineWidth(.22);doc.rect(x,y,w,headH+bodyH);doc.line(x+timeW,y,x+timeW,y+headH+bodyH);for(let i=1;i<7;i++){const vx=x+timeW+i*dayW;doc.line(vx,y,vx,y+headH+bodyH)}doc.setFont("helvetica","bold");doc.setFontSize(7);doc.setTextColor(25,73,57);DAYS.forEach((name,i)=>{const d=addDays(data.start,i),cx=x+timeW+i*dayW+dayW/2;doc.text(name,cx,y+4.8,{align:"center"});doc.setFont("helvetica","normal");doc.setFontSize(6);doc.setTextColor(100,112,106);doc.text(`${d.getDate()} ${MONTHS[d.getMonth()].slice(0,4)}.`,cx,y+9,{align:"center"});doc.setFont("helvetica","bold");doc.setFontSize(7);doc.setTextColor(25,73,57)});doc.setFont("helvetica","normal");for(let h=START_HOUR;h<=END_HOUR;h++){const yy=bodyY+(h-START_HOUR)*hourH;doc.setDrawColor(178,178,178);doc.setLineWidth(.2);doc.line(x,yy,x+w,yy);if(h<END_HOUR){const hy=yy+hourH/2;doc.setDrawColor(214,214,214);doc.setLineWidth(.12);doc.line(x+timeW,hy,x+w,hy)}doc.setFontSize(6);doc.setTextColor(85,94,89);doc.text(`${pad(h)}:00`,x+timeW-1.4,yy+1.8,{align:"right"})}data.groups.forEach((list,day)=>{list.forEach(item=>{const s=Math.max(START_HOUR*60,timeToMin(item.start)),e=Math.min(END_HOUR*60,Math.max(s+15,timeToMin(item.end)));if(e<=START_HOUR*60||s>=END_HOUR*60)return;const ex=x+timeW+day*dayW+1,ey=bodyY+((s-START_HOUR*60)/60)*hourH,eh=Math.max(4.8,((e-s)/60)*hourH),ew=dayW-2;doc.setFillColor(232,245,238);doc.setDrawColor(76,156,114);doc.setLineWidth(.25);doc.roundedRect(ex,ey,ew,eh,1.2,1.2,"FD");doc.setFillColor(8,118,84);doc.rect(ex,ey,1,eh,"F");doc.setTextColor(7,93,67);doc.setFont("helvetica","bold");doc.setFontSize(5.5);doc.text(`${item.start} - ${item.end}`,ex+2,ey+2.6,{maxWidth:ew-3});if(eh>=7){doc.setTextColor(23,59,48);doc.setFontSize(6);const title=doc.splitTextToSize(String(item.task||"Intervention"),ew-3).slice(0,2);doc.text(title,ex+2,ey+5.2)}if(item.site&&eh>=12){doc.setFont("helvetica","normal");doc.setTextColor(82,102,93);doc.setFontSize(5);const site=doc.splitTextToSize(String(item.site),ew-3).slice(0,2);doc.text(site,ex+2,ey+9)}doc.setFont("helvetica","normal")})});doc.setTextColor(95,110,103);doc.setFontSize(6);const total=data.groups.reduce((n,g)=>n+g.length,0);doc.text(total?`${total} intervention(s) planifiée(s)`:"Planning vide - aucune intervention planifiée",8,204);doc.text("Document généré depuis Inovtec Dashboard",289,204,{align:"right"})}
function drawPage(doc,data){drawHeader(doc,data);drawGrid(doc,data)}
function makeDoc(){const C=jsPDFClass();if(!C){alert("Le générateur PDF n’est pas encore chargé. Réessaie dans quelques secondes.");return null}return new C({orientation:"landscape",unit:"mm",format:"a4",compress:true})}
function single(){const state=loadState(),week=currentWeek(),agent=state.agents.find(a=>String(a.id)===String(state.selected));if(!week){alert("La semaine affichée n’a pas pu être déterminée.");return}if(!agent){alert("Sélectionne d’abord un agent dans la liste de gauche.");return}const doc=makeDoc();if(!doc)return;const data=agentData(state,week,agent);drawPage(doc,data);doc.save(`Planning_${safeName(data.agent)}_${data.start.getFullYear()}-${pad(data.start.getMonth()+1)}-${pad(data.start.getDate())}.pdf`)}
function all(){const state=loadState(),week=currentWeek(),agents=Array.isArray(state.agents)?state.agents.slice():[];if(!week){alert("La semaine affichée n’a pas pu être déterminée.");return}if(!agents.length){alert("Aucun agent n’est disponible dans le Planning.");return}const queue=[];const maxCopies=Math.max(...agents.map(copiesFor),2);for(let round=1;round<=maxCopies;round++)agents.forEach(a=>{if(copiesFor(a)>=round)queue.push(a)});if(!queue.length)return;const doc=makeDoc();if(!doc)return;queue.forEach((agent,i)=>{if(i>0)doc.addPage("a4","landscape");drawPage(doc,agentData(state,week,agent))});const start=dateFromWeek(week,0);doc.save(`Plannings_tous_agents_${start.getFullYear()}-${pad(start.getMonth()+1)}-${pad(start.getDate())}.pdf`)}
window.InovtecPlanningPDF={generate:single,generateSingle:single,generateAll:all,copiesFor};
})();