(()=>{
"use strict";
const KEY="inovtec_plannings_v2", UI_KEY="inovtec_planning_ui_v4";
const COLORS=["#68b253","#4c92df","#7b5ac8","#e7832d","#e65f70","#59b9c4","#f0b43a","#6a83c7"];
const DAYS=["Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi","Dimanche"];
const MONTHS=["janvier","février","mars","avril","mai","juin","juillet","août","septembre","octobre","novembre","décembre"];
const START_HOUR=6, END_HOUR=22, HOUR_PX=64;
const $=id=>document.getElementById(id), pad=n=>String(n).padStart(2,"0");
let state={agents:[],weeks:{},selected:null};
let ui={view:"week",anchor:toISODate(new Date()),hidden:[]};
let editRef=null,longPressTimer=null;

function uid(prefix){return prefix+"_"+Date.now()+"_"+Math.random().toString(16).slice(2)}
function safeJSON(raw,fallback){try{return JSON.parse(raw)}catch{return fallback}}
function syncSingleAgentSelection(){ui.hidden=state.agents.filter(a=>a.id!==state.selected).map(a=>a.id)}
function load(){
  const saved=safeJSON(localStorage.getItem(KEY),null);if(saved&&Array.isArray(saved.agents)&&saved.weeks)state=saved;
  if(!state.agents.length){const id=uid("a");state.agents=[{id,name:"Agent 1",copies:1,color:COLORS[0]}];state.selected=id}
  state.agents.forEach((a,i)=>{if(!a.color)a.color=COLORS[i%COLORS.length]});
  if(!state.agents.some(a=>a.id===state.selected))state.selected=state.agents[0]?.id||null;
  const uiSaved=safeJSON(localStorage.getItem(UI_KEY),null);if(uiSaved)ui={...ui,...uiSaved};
  if(!["day","week","month","list"].includes(ui.view))ui.view="week";
  if(!/^\d{4}-\d{2}-\d{2}$/.test(ui.anchor||""))ui.anchor=toISODate(new Date());
  if(!Array.isArray(ui.hidden))ui.hidden=[];
  syncSingleAgentSelection();
}
function save(){localStorage.setItem(KEY,JSON.stringify(state));updateMeta()}
function saveUI(){localStorage.setItem(UI_KEY,JSON.stringify(ui))}
function toISODate(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function parseDate(s){const [y,m,d]=String(s).split("-").map(Number);return new Date(y,m-1,d)}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function mondayOf(d){const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}
function isoWeekKey(d){const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()+3-((x.getDay()+6)%7));const y=x.getFullYear();const w1=new Date(y,0,4);const week=1+Math.round(((x-w1)/86400000-3+((w1.getDay()+6)%7))/7);return `${y}-W${pad(week)}`}
function weekStartFromKey(key){const m=String(key).match(/^(\d{4})-W(\d{2})$/);if(!m)return mondayOf(new Date());const y=+m[1],w=+m[2],jan4=new Date(y,0,4);const mon=mondayOf(jan4);return addDays(mon,(w-1)*7)}
function dayIndex(d){return (d.getDay()+6)%7}
function minutes(t){const [h,m]=String(t||"00:00").split(":").map(Number);return h*60+m}
function timeFromMinutes(v){v=Math.max(0,Math.min(1439,v));return `${pad(Math.floor(v/60))}:${pad(v%60)}`}
function snap(v,step=15){return Math.round(v/step)*step}
function agentById(id){return state.agents.find(a=>a.id===id)}
function visibleAgents(){const a=agentById(state.selected);return a?[a]:[]}
function eventsForDate(date){const key=isoWeekKey(date),di=dayIndex(date);return (state.weeks[key]||[]).filter(e=>Number(e.day)===di&&e.agentId===state.selected).map(e=>({...e,weekKey:key,date}))}
function currentRange(){const a=parseDate(ui.anchor);if(ui.view==="day")return [a,a];if(ui.view==="week"){const m=mondayOf(a);return [m,addDays(m,6)]}return [new Date(a.getFullYear(),a.getMonth(),1),new Date(a.getFullYear(),a.getMonth()+1,0)]}
function formatRange(){const [a,b]=currentRange();if(ui.view==="day")return `${DAYS[dayIndex(a)]} ${a.getDate()} ${MONTHS[a.getMonth()]} ${a.getFullYear()}`;if(ui.view==="week"){if(a.getMonth()===b.getMonth())return `${a.getDate()} – ${b.getDate()} ${MONTHS[a.getMonth()]} ${b.getFullYear()}`;return `${a.getDate()} ${MONTHS[a.getMonth()]} – ${b.getDate()} ${MONTHS[b.getMonth()]} ${b.getFullYear()}`}return `${MONTHS[a.getMonth()][0].toUpperCase()+MONTHS[a.getMonth()].slice(1)} ${a.getFullYear()}`}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}

function selectAgent(id){if(!agentById(id))return;state.selected=id;syncSingleAgentSelection();save();saveUI();closePopover();hideMenus();render()}
function render(){
  $("rangeLabel").textContent=formatRange();document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===ui.view));
  const selected=agentById(state.selected);const heading=document.querySelector(".planner-top h2");if(heading)heading.textContent=selected?`Planning — ${selected.name}`:"Planning";
  renderAgents();renderLegend();renderAgentSelect();
  if(ui.view==="week")renderTimeView(7);else if(ui.view==="day")renderTimeView(1);else if(ui.view==="month")renderMonth();else renderList();
  saveUI();updateMeta();requestAnimationFrame(scrollToUsefulTime);
}
function renderAgents(){const q=$("agentSearch").value.trim().toLowerCase(),box=$("agentList");box.innerHTML="";state.agents.filter(a=>a.name.toLowerCase().includes(q)).forEach(a=>{const row=document.createElement("div");row.className="agent-row"+(a.id===state.selected?" active":"");row.dataset.agentId=a.id;row.innerHTML=`<button class="agent-toggle" type="button" style="background:${escapeHtml(a.color)}" aria-label="Sélectionner cet agent"></button><span class="agent-name">${escapeHtml(a.name)}</span>`;row.querySelector(".agent-toggle").onclick=e=>{e.stopPropagation();selectAgent(a.id)};row.onclick=()=>selectAgent(a.id);row.oncontextmenu=e=>{e.preventDefault();state.selected=a.id;syncSingleAgentSelection();save();saveUI();renderAgents();showAgentMenu(a.id,e.clientX,e.clientY)};row.addEventListener("pointerdown",e=>{if(e.pointerType==="mouse")return;clearTimeout(longPressTimer);longPressTimer=setTimeout(()=>{state.selected=a.id;syncSingleAgentSelection();save();saveUI();renderAgents();showAgentMenu(a.id,e.clientX,e.clientY)},520)});row.addEventListener("pointerup",()=>clearTimeout(longPressTimer));row.addEventListener("pointercancel",()=>clearTimeout(longPressTimer));box.appendChild(row)})}
function toggleAgent(id){selectAgent(id)}
function renderLegend(){const box=$("legend");box.innerHTML=visibleAgents().map(a=>`<span class="legend-item"><i class="legend-dot" style="background:${escapeHtml(a.color)}"></i>${escapeHtml(a.name)}</span>`).join("")}
function renderAgentSelect(){const s=$("evAgent");s.innerHTML=state.agents.map(a=>`<option value="${escapeHtml(a.id)}">${escapeHtml(a.name)}</option>`).join("");if(state.selected)s.value=state.selected}

function renderTimeView(dayCount){
  const anchor=parseDate(ui.anchor),dates=dayCount===7?Array.from({length:7},(_,i)=>addDays(mondayOf(anchor),i)):[anchor];
  const host=$("viewHost"),today=toISODate(new Date());host.style.setProperty("--days",dayCount);
  host.innerHTML=`<section class="${dayCount===7?"week-view":"day-view"}"><div class="cal-head" style="--days:${dayCount}"><div class="blank"></div>${dates.map(d=>{const t=toISODate(d)===today;return `<div class="day-head ${t?"today":""}"><span>${DAYS[dayIndex(d)].slice(0,3).toLowerCase()}.</span><span class="date-dot">${d.getDate()}</span><span>${MONTHS[d.getMonth()].slice(0,4)}</span></div>`}).join("")}</div><div class="calendar-scroll"><div class="time-grid" style="--days:${dayCount}"><div class="hours">${Array.from({length:END_HOUR-START_HOUR+1},(_,i)=>`<span class="hour-label" style="top:${i*HOUR_PX}px">${pad(START_HOUR+i)}:00</span>`).join("")}</div>${dates.map(d=>`<div class="day-column" data-date="${toISODate(d)}"></div>`).join("")}</div></div></section>`;
  const cols=[...host.querySelectorAll(".day-column")];cols.forEach((col,i)=>{const date=dates[i];col.ondblclick=e=>{if(e.target!==col)return;const r=col.getBoundingClientRect(),mins=snap(START_HOUR*60+((e.clientY-r.top)/HOUR_PX)*60);openNewEvent(date,mins,e.clientX,e.clientY)};eventsForDate(date).forEach(ev=>col.appendChild(makeEventEl(ev)))});
  const now=new Date();if(dates.some(d=>toISODate(d)===today)&&now.getHours()>=START_HOUR&&now.getHours()<END_HOUR){const col=cols[dates.findIndex(d=>toISODate(d)===today)];if(col){const line=document.createElement("div");line.className="now-line";line.style.top=`${((now.getHours()*60+now.getMinutes()-START_HOUR*60)/60)*HOUR_PX}px`;col.appendChild(line)}}
}
function makeEventEl(ev){
  const a=agentById(ev.agentId)||{color:"#6b8f77",name:"Agent"},sm=minutes(ev.start),em=minutes(ev.end),top=((sm-START_HOUR*60)/60)*HOUR_PX,height=Math.max(22,((em-sm)/60)*HOUR_PX-3);const el=document.createElement("article");el.className="event";el.dataset.eventId=ev.id;el.dataset.weekKey=ev.weekKey;el.style.cssText=`--event-color:${a.color};top:${top}px;height:${height}px`;el.innerHTML=`<div class="event-time">${escapeHtml(ev.start)} – ${escapeHtml(ev.end)}</div><div class="event-title">${escapeHtml(ev.task||"Intervention")}</div>${ev.site?`<div class="event-site">${escapeHtml(ev.site)}</div>`:""}<div class="resize-handle" title="Ajuster la durée"></div>`;el.onclick=e=>{e.stopPropagation();if(e.target.classList.contains("resize-handle"))return;openEditEvent(ev,el)};bindDrag(el,ev);bindResize(el,ev);return el
}
function bindDrag(el,ev){let startX=0,startY=0,moved=false,ghost=null;el.addEventListener("pointerdown",e=>{if(e.button!==0||e.target.classList.contains("resize-handle"))return;startX=e.clientX;startY=e.clientY;moved=false;el.setPointerCapture?.(e.pointerId);const move=me=>{if(Math.hypot(me.clientX-startX,me.clientY-startY)<5&&!moved)return;moved=true;if(!ghost){ghost=el.cloneNode(true);ghost.classList.add("drag-ghost");ghost.style.width=el.getBoundingClientRect().width+"px";ghost.style.height=el.getBoundingClientRect().height+"px";document.body.appendChild(ghost)}ghost.style.left=(me.clientX+10)+"px";ghost.style.top=(me.clientY+10)+"px"};const up=ue=>{el.removeEventListener("pointermove",move);el.removeEventListener("pointerup",up);el.removeEventListener("pointercancel",up);ghost?.remove();if(!moved)return;const target=document.elementFromPoint(ue.clientX,ue.clientY)?.closest?.(".day-column");if(!target)return;const r=target.getBoundingClientRect(),dur=Math.max(15,minutes(ev.end)-minutes(ev.start));let start=snap(START_HOUR*60+((ue.clientY-r.top)/HOUR_PX)*60);start=Math.max(START_HOUR*60,Math.min(END_HOUR*60-dur,start));moveEvent(ev,target.dataset.date,start,dur)};el.addEventListener("pointermove",move);el.addEventListener("pointerup",up);el.addEventListener("pointercancel",up)})}
function bindResize(el,ev){const h=el.querySelector(".resize-handle");h.addEventListener("pointerdown",e=>{e.stopPropagation();e.preventDefault();const initial=minutes(ev.end),startY=e.clientY;h.setPointerCapture?.(e.pointerId);const move=me=>{const delta=snap(((me.clientY-startY)/HOUR_PX)*60);const end=Math.max(minutes(ev.start)+15,Math.min(END_HOUR*60,initial+delta));el.style.height=Math.max(22,((end-minutes(ev.start))/60)*HOUR_PX-3)+"px";el.dataset.previewEnd=timeFromMinutes(end)};const up=()=>{h.removeEventListener("pointermove",move);h.removeEventListener("pointerup",up);const end=el.dataset.previewEnd;if(end){const original=findEvent(ev.weekKey,ev.id);if(original){original.end=end;save();render()}}};h.addEventListener("pointermove",move);h.addEventListener("pointerup",up)})}
function moveEvent(ev,dateStr,startMin,dur){const original=findEvent(ev.weekKey,ev.id);if(!original)return;state.weeks[ev.weekKey]=state.weeks[ev.weekKey].filter(x=>x.id!==ev.id);const d=parseDate(dateStr),newKey=isoWeekKey(d);if(!state.weeks[newKey])state.weeks[newKey]=[];original.day=dayIndex(d);original.start=timeFromMinutes(startMin);original.end=timeFromMinutes(startMin+dur);state.weeks[newKey].push(original);save();render()}

function renderMonth(){
  const host=$("viewHost"),a=parseDate(ui.anchor),first=new Date(a.getFullYear(),a.getMonth(),1),gridStart=mondayOf(first),today=toISODate(new Date());const dates=Array.from({length:42},(_,i)=>addDays(gridStart,i));
  host.innerHTML=`<div class="month-view"><div class="month-grid">${DAYS.map(d=>`<div class="month-weekday">${d}</div>`).join("")}${dates.map(d=>{const outside=d.getMonth()!==a.getMonth(),isToday=toISODate(d)===today,events=eventsForDate(d).sort((x,y)=>x.start.localeCompare(y.start));return `<div class="month-cell ${outside?"outside":""} ${isToday?"today":""}" data-date="${toISODate(d)}"><div class="month-num">${d.getDate()}</div>${events.slice(0,3).map(ev=>{const ag=agentById(ev.agentId)||{color:"#6b8f77"};return `<div class="month-event" data-id="${escapeHtml(ev.id)}" data-week="${escapeHtml(ev.weekKey)}" style="--event-color:${ag.color}">${escapeHtml(ev.start)} ${escapeHtml(ev.task||"Intervention")}</div>`}).join("")}${events.length>3?`<div class="more-events">+ ${events.length-3} autre${events.length-3>1?"s":""}</div>`:""}</div>`}).join("")}</div></div>`;
  host.querySelectorAll(".month-cell").forEach(cell=>cell.ondblclick=e=>{if(e.target.closest(".month-event"))return;openNewEvent(parseDate(cell.dataset.date),9*60,e.clientX,e.clientY)});host.querySelectorAll(".month-event").forEach(el=>el.onclick=e=>{e.stopPropagation();const ev=findEventExpanded(el.dataset.week,el.dataset.id);if(ev)openEditEvent(ev,el)})
}
function renderList(){
  const host=$("viewHost"),[start,end]=currentRange(),days=[],today=toISODate(new Date());for(let d=new Date(start);d<=end;d=addDays(d,1)){const events=eventsForDate(d).sort((a,b)=>a.start.localeCompare(b.start));if(events.length)days.push({date:new Date(d),events})}
  if(!days.length){host.innerHTML='<div class="empty-state">Aucune intervention sur cette période.</div>';return}
  host.innerHTML=`<div class="list-view">${days.map(({date,events})=>`<section class="agenda-day"><div class="agenda-date ${toISODate(date)===today?"today":""}">${DAYS[dayIndex(date)]}<br>${date.getDate()} ${MONTHS[date.getMonth()]}</div><div class="agenda-items">${events.map(ev=>{const ag=agentById(ev.agentId)||{color:"#6b8f77",name:"Agent"};return `<div class="agenda-item" data-id="${escapeHtml(ev.id)}" data-week="${escapeHtml(ev.weekKey)}" style="--event-color:${ag.color}"><span class="agenda-time">${escapeHtml(ev.start)}<br>${escapeHtml(ev.end)}</span><i class="agenda-dot"></i><span class="agenda-copy"><strong>${escapeHtml(ev.task||"Intervention")}</strong><span>${escapeHtml(ag.name)}${ev.site?" · "+escapeHtml(ev.site):""}</span></span></div>`}).join("")}</div></section>`).join("")}</div>`;host.querySelectorAll(".agenda-item").forEach(el=>el.onclick=()=>{const ev=findEventExpanded(el.dataset.week,el.dataset.id);if(ev)openEditEvent(ev,el)})
}
function scrollToUsefulTime(){if(!["week","day"].includes(ui.view))return;const s=document.querySelector(".calendar-scroll");if(s&&!s.dataset.scrolled){s.scrollTop=Math.max(0,(7-START_HOUR)*HOUR_PX-20);s.dataset.scrolled="1"}}

function findEvent(weekKey,id){return (state.weeks[weekKey]||[]).find(e=>e.id===id)}
function findEventExpanded(weekKey,id){const e=findEvent(weekKey,id);if(!e)return null;return {...e,weekKey,date:addDays(weekStartFromKey(weekKey),Number(e.day)||0)}}
function openNewEvent(date,startMin,x,y){const agent=agentById(state.selected)||state.agents[0];if(!agent)return;editRef=null;$("evTitle").value="";$("evAgent").value=agent.id;$("evDate").value=toISODate(date);$("evStart").value=timeFromMinutes(Math.max(START_HOUR*60,Math.min(END_HOUR*60-60,startMin)));$("evEnd").value=timeFromMinutes(Math.max(START_HOUR*60+30,Math.min(END_HOUR*60,startMin+60)));$("evSite").value="";$("evNote").value="";$("evDelete").classList.add("hidden");showPopover(x,y,agent.color);setTimeout(()=>$("evTitle").focus(),20)}
function openEditEvent(ev,anchor){const agent=agentById(ev.agentId)||state.agents[0];editRef={weekKey:ev.weekKey,id:ev.id};$("evTitle").value=ev.task||"";$("evAgent").value=ev.agentId;$("evDate").value=toISODate(ev.date);$("evStart").value=ev.start||"08:00";$("evEnd").value=ev.end||"09:00";$("evSite").value=ev.site||"";$("evNote").value=ev.note||"";$("evDelete").classList.remove("hidden");const r=anchor.getBoundingClientRect();showPopover(r.left+r.width/2,r.top+r.height/2,agent?.color||"#2b7d3d")}
function showPopover(x,y,color){hideMenus();const p=$("eventPopover");p.style.setProperty("--event-color",color);p.classList.remove("hidden");requestAnimationFrame(()=>{const r=p.getBoundingClientRect(),left=Math.max(8,Math.min(innerWidth-r.width-8,x-r.width/2)),top=Math.max(8,Math.min(innerHeight-r.height-8,y-r.height/2));p.style.left=left+"px";p.style.top=top+"px"})}
function closePopover(){$("eventPopover").classList.add("hidden");editRef=null}
function saveEventFromForm(){const title=$("evTitle").value.trim();if(!title)return false;const start=$("evStart").value,end=$("evEnd").value;if(minutes(end)<=minutes(start)){alert("L’heure de fin doit être après l’heure de début.");return false}const date=parseDate($("evDate").value),newKey=isoWeekKey(date),data={agentId:$("evAgent").value,day:dayIndex(date),start,end,task:title,site:$("evSite").value.trim(),note:$("evNote").value.trim()};if(editRef){const old=findEvent(editRef.weekKey,editRef.id);if(!old)return false;state.weeks[editRef.weekKey]=state.weeks[editRef.weekKey].filter(e=>e.id!==editRef.id);if(!state.weeks[newKey])state.weeks[newKey]=[];state.weeks[newKey].push({...old,...data})}else{if(!state.weeks[newKey])state.weeks[newKey]=[];state.weeks[newKey].push({id:uid("e"),...data})}state.selected=data.agentId;syncSingleAgentSelection();save();saveUI();closePopover();render();return true}
function deleteEditedEvent(){if(!editRef)return;const ev=findEvent(editRef.weekKey,editRef.id);if(!ev||!confirm(`Supprimer « ${ev.task||"cette intervention"} » ?`))return;state.weeks[editRef.weekKey]=state.weeks[editRef.weekKey].filter(e=>e.id!==editRef.id);save();closePopover();render()}

function showAgentMenu(id,x,y){hideMenus();const a=agentById(id);if(!a)return;const m=$("contextMenu");m.innerHTML=`<button class="ctx-item" data-act="rename" type="button">Modifier le nom</button><div class="color-row">${COLORS.map(c=>`<button class="color-swatch" type="button" data-color="${c}" style="background:${c}" title="Couleur"></button>`).join("")}</div><button class="ctx-item" data-act="duplicate" type="button">Dupliquer l’agent</button><div class="ctx-sep"></div><button class="ctx-item danger" data-act="delete" type="button">Supprimer</button>`;m.classList.remove("hidden");placeMenu(m,x,y);m.querySelector('[data-act="rename"]').onclick=()=>renameAgent(id);m.querySelector('[data-act="duplicate"]').onclick=()=>duplicateAgent(id);m.querySelector('[data-act="delete"]').onclick=()=>deleteAgent(id);m.querySelectorAll("[data-color]").forEach(b=>b.onclick=()=>{a.color=b.dataset.color;save();hideMenus();render()})}
function showBlankMenu(x,y){hideMenus();const m=$("contextMenu");m.innerHTML='<button class="ctx-item" data-act="new" type="button">Nouvel agent</button>';m.classList.remove("hidden");placeMenu(m,x,y);m.querySelector('[data-act="new"]').onclick=createAgent}
function placeMenu(m,x,y){requestAnimationFrame(()=>{const r=m.getBoundingClientRect();m.style.left=Math.max(6,Math.min(innerWidth-r.width-6,x))+"px";m.style.top=Math.max(6,Math.min(innerHeight-r.height-6,y))+"px"})}
function hideMenus(){$("contextMenu").classList.add("hidden");$("moreMenu").classList.add("hidden")}
function createAgent(){const name=prompt("Nom de l’agent :");if(!name?.trim())return;const a={id:uid("a"),name:name.trim(),copies:1,color:COLORS[state.agents.length%COLORS.length]};state.agents.push(a);state.selected=a.id;syncSingleAgentSelection();save();saveUI();hideMenus();render()}
function renameAgent(id){const a=agentById(id);if(!a)return;const name=prompt("Nom de l’agent :",a.name);if(name?.trim()){a.name=name.trim();save();hideMenus();render()}}
function duplicateAgent(id){const a=agentById(id);if(!a)return;const copy={...a,id:uid("a"),name:a.name+" copie",color:COLORS[(state.agents.indexOf(a)+1)%COLORS.length]};state.agents.push(copy);state.selected=copy.id;syncSingleAgentSelection();save();saveUI();hideMenus();render()}
function deleteAgent(id){const a=agentById(id);if(!a)return;if(state.agents.length===1){alert("Il faut conserver au moins un agent.");return}if(!confirm(`Supprimer ${a.name} et toutes ses interventions ?`))return;state.agents=state.agents.filter(x=>x.id!==id);Object.keys(state.weeks).forEach(k=>state.weeks[k]=(state.weeks[k]||[]).filter(e=>e.agentId!==id));state.selected=state.agents[0]?.id||null;syncSingleAgentSelection();save();saveUI();hideMenus();render()}

function navigate(dir){const a=parseDate(ui.anchor);if(ui.view==="day")ui.anchor=toISODate(addDays(a,dir));else if(ui.view==="week")ui.anchor=toISODate(addDays(a,dir*7));else ui.anchor=toISODate(new Date(a.getFullYear(),a.getMonth()+dir,Math.min(a.getDate(),28)));render()}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`inovtec_plannings_${toISODate(new Date())}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function importData(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.agents)||!x.weeks)throw Error("format incompatible");state=x;state.agents.forEach((a,i)=>{if(!a.color)a.color=COLORS[i%COLORS.length]});if(!state.agents.some(a=>a.id===state.selected))state.selected=state.agents[0]?.id||null;syncSingleAgentSelection();save();saveUI();render();alert("Import réussi.")}catch(err){alert("Import impossible : "+err.message)}};r.readAsText(file)}
function updateMeta(){const [a,b]=currentRange(),events=[];for(let d=new Date(a);d<=b;d=addDays(d,1))events.push(...eventsForDate(d));$("title").textContent=agentById(state.selected)?.name||"Agent";$("weekInfo").textContent=formatRange();$("count").textContent=`${events.length} intervention${events.length>1?"s":""}`;$("rows").innerHTML=events.map(e=>`<tr><td>${DAYS[Number(e.day)||0]}</td><td>${escapeHtml(e.start)} – ${escapeHtml(e.end)}</td></tr>`).join("")}

$("eventForm").onsubmit=e=>{e.preventDefault();saveEventFromForm()};$("evDelete").onclick=deleteEditedEvent;
$("agentSearch").oninput=renderAgents;$("sidebar").oncontextmenu=e=>{if(e.target.closest(".agent-row")||e.target.closest("input"))return;e.preventDefault();showBlankMenu(e.clientX,e.clientY)};
$("prevBtn").onclick=()=>navigate(-1);$("nextBtn").onclick=()=>navigate(1);$("todayBtn").onclick=()=>{ui.anchor=toISODate(new Date());render()};
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{ui.view=b.dataset.view;render()});
$("moreBtn").onclick=e=>{e.stopPropagation();const m=$("moreMenu"),r=$("moreBtn").getBoundingClientRect();if(!m.classList.contains("hidden")){m.classList.add("hidden");return}hideMenus();m.classList.remove("hidden");placeMenu(m,r.right-150,r.bottom+5)};
$("importAction").onclick=()=>{$("importFile").click();hideMenus()};$("exportAction").onclick=()=>{exportData();hideMenus()};$("printAction").onclick=()=>{hideMenus();print()};$("importFile").onchange=e=>{importData(e.target.files?.[0]);e.target.value=""};
$("addAgent").onclick=createAgent;$("exportBtn").onclick=exportData;$("printBtn").onclick=()=>print();
document.addEventListener("pointerdown",e=>{if(!e.target.closest(".context-menu")&&!e.target.closest("#moreBtn")&&!e.target.closest(".more-menu"))hideMenus();if(!e.target.closest(".popover")&&!e.target.closest(".event")&&!e.target.closest(".month-event")&&!e.target.closest(".agenda-item")&&!$("eventPopover").classList.contains("hidden"))closePopover()});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closePopover();hideMenus()}});
window.addEventListener("storage",e=>{if(e.key===KEY){load();render()}});
load();render();
})();