import { chromium } from 'playwright';

const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
let failures=0;
const check=(condition,message)=>{if(!condition)throw Error(message)};
try{
 const context=await browser.newContext({serviceWorkers:'block'});
 await context.addInitScript(()=>{
  const item={id:'m_test',name:'Sacs aspirateur',reference:'SAC-01',supplier:'Fournisseur Test',site:'Améthyste',quantity:1,minStock:4,price:10};
  const doc={moduleSyncV1:{materiel:{payload:JSON.stringify({items:[item]}),updatedAt:'2026-09-17T08:00:00Z'}}};
  const state={doc,writes:0,cache:false,listeners:[]};window.__reassortTest=state;
  const deepMerge=(a,b)=>{for(const [k,v] of Object.entries(b)){if(v&&typeof v==='object'&&!Array.isArray(v))a[k]=deepMerge({...a[k]},v);else a[k]=v}return a};
  const snap=()=>({exists:true,data:()=>structuredClone(state.doc),metadata:{fromCache:state.cache,hasPendingWrites:false}});
  const emit=()=>queueMicrotask(()=>state.listeners.forEach(cb=>cb(snap())));
  const ref={onSnapshot(options,cb){state.listeners.push(cb);queueMicrotask(()=>cb(snap()));return()=>{state.listeners=state.listeners.filter(x=>x!==cb)}},get(){return Promise.resolve(snap())}};
  const db={collection:name=>({doc:uid=>{if(name!=='kanban'||uid!=='test-user')throw Error('Incorrect Firebase path');return ref}}),async runTransaction(fn){let update=null;const tx={get:async()=>snap(),set:(docRef,changes,options)=>{if(docRef!==ref||!options?.merge)throw Error('Transaction incorrecte');update=changes}};const result=await fn(tx);if(update){deepMerge(state.doc,update);state.writes++;emit()}return result}};
  window.firebase={apps:[],initializeApp(){this.apps.push({})},auth(){return {onAuthStateChanged(cb){queueMicrotask(()=>cb({uid:'test-user'}));return()=>{}},signInWithEmailAndPassword(){return Promise.resolve()}}},firestore(){return db}};
  window.INOVTEC_FIREBASE_CONFIG={projectId:'fake'};
 });
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://www.gstatic.com/firebasejs/**',route=>route.fulfill({status:200,contentType:'application/javascript',body:''}));
 await page.route('**/firebase-config.js*',route=>route.fulfill({status:200,contentType:'application/javascript',body:'window.INOVTEC_FIREBASE_CONFIG={projectId:"fake"};'}));
 await page.goto('http://127.0.0.1:8765/REASSORT.html',{waitUntil:'domcontentloaded',timeout:30000});
 await page.waitForFunction(()=>document.querySelector('#syncStatus')?.textContent?.includes('Firebase synchronisé'),{timeout:15000});
 check(await page.locator('#kLow').innerText()==='1','Low-stock indicator missing');
 console.log('OK : affichage et connexion simulée du dashboard');
 await page.locator('[data-tab="besoins"]').click();
 await page.locator('[data-action="suggest"]').click();
 check(await page.locator('#orderQty').inputValue()==='7','Suggested quantity should reach double minimum (8 - 1)');
 await page.locator('#orderExpected').fill('2026-09-25');
 await page.locator('#orderForm button[type="submit"]').click();
 await page.waitForFunction(()=>JSON.parse(window.__reassortTest.doc.moduleSyncV1.reassort.payload).orders.length===1);
 check(await page.locator('#kPending').innerText()==='1','Order not displayed as pending');
 console.log('OK : suggestion et commande sauvegardée');
 await page.locator('[data-tab="receptions"]').click();
 await page.locator('#receiptOrder').selectOption({index:1});
 await page.locator('#receiptQty').fill('2');
 await page.locator('#receiptPrice').fill('10');
 await page.locator('#receiptRef').fill('BL-1');
 await page.locator('#receiveBtn').click();
 await page.waitForFunction(()=>JSON.parse(window.__reassortTest.doc.moduleSyncV1.reassort.payload).deliveries.length===1);
 let state=await page.evaluate(()=>({orders:JSON.parse(window.__reassortTest.doc.moduleSyncV1.reassort.payload).orders,stock:JSON.parse(window.__reassortTest.doc.moduleSyncV1.materiel.payload).items[0].quantity}));
 check(state.stock===3,'First partial delivery did not increment material stock');
 check(state.orders[0].status==='partielle','Partial delivery status incorrect');
 console.log('OK : première réception partielle et stock actualisé');
 await page.locator('[data-tab="receptions"]').click();
 await page.locator('#receiptOrder').selectOption({index:1});
 await page.locator('#receiptQty').fill('5');
 await page.locator('#receiveBtn').click();
 await page.waitForFunction(()=>JSON.parse(window.__reassortTest.doc.moduleSyncV1.reassort.payload).deliveries.length===2);
 state=await page.evaluate(()=>({orders:JSON.parse(window.__reassortTest.doc.moduleSyncV1.reassort.payload).orders,stock:JSON.parse(window.__reassortTest.doc.moduleSyncV1.materiel.payload).items[0].quantity}));
 check(state.stock===8,'Final delivery did not increment stock correctly');
 check(state.orders[0].status==='recue','Completed order status incorrect');
 check(await page.locator('#kDeliveries').innerText()==='2','Delivery history counter incorrect');
 check(await page.locator('#historyRows tr').count()===2,'Two receipts not visible in history');
 console.log('OK : commande complète, historique double, stock sans double comptage');
 await page.evaluate(()=>{window.__reassortTest.cache=true;window.__reassortTest.listeners.forEach(cb=>cb({exists:true,data:()=>structuredClone(window.__reassortTest.doc),metadata:{fromCache:true,hasPendingWrites:false}}))});
 check(await page.locator('#saveDraft').isDisabled(),'Offline write guard missing');
 check(errors.length===0,'JavaScript errors: '+errors.join('; '));
 console.log('OK : écritures bloquées en mode cache, aucune erreur JavaScript');
 await context.close();
}catch(e){failures++;console.error('ÉCHEC RÉASSORT : '+String(e?.stack||e))}finally{await browser.close()}
if(failures)process.exitCode=1;
