import {chromium} from 'playwright';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const check=(v,message)=>{if(!v)throw Error(message)};
try{
 const context=await browser.newContext({serviceWorkers:'block'});
 await context.addInitScript(()=>{
  const item={id:'m_test',name:'Sacs aspirateur',reference:'SAC-01',supplier:'Fournisseur Test',site:'Améthyste',quantity:9,minStock:4,price:10};
  const legacy={id:'old-order',name:'Ancien achat',supplier:'Fournisseur Test',site:'Dépôt',quantity:5,status:'recue'};
  const prior={id:'old-receipt',orderId:'old-order',date:new Date().toISOString().slice(0,10),name:'Ancien achat',supplier:'Fournisseur Test',site:'Dépôt',quantity:5};
  const doc={moduleSyncV1:{materiel:{payload:JSON.stringify({items:[item]})},reassort:{payload:JSON.stringify({orders:[legacy],deliveries:[prior]})}}};
  const state={doc,writes:0,cache:false,listeners:[]};window.__reassortTest=state;
  const merge=(a,b)=>{for(const [k,v] of Object.entries(b)){if(v&&typeof v==='object'&&!Array.isArray(v))a[k]=merge({...a[k]},v);else a[k]=v}return a};
  const snap=()=>({exists:true,data:()=>structuredClone(state.doc),metadata:{fromCache:state.cache,hasPendingWrites:false}});
  const emit=()=>queueMicrotask(()=>state.listeners.forEach(cb=>cb(snap())));
  const ref={onSnapshot(options,cb){state.listeners.push(cb);queueMicrotask(()=>cb(snap()));return()=>{state.listeners=state.listeners.filter(f=>f!==cb)}},get:async()=>snap()};
  const sites={onSnapshot(cb){queueMicrotask(()=>cb({docs:[{id:'site-1',data:()=>({nom:'Améthyste'})},{id:'site-2',data:()=>({nom:'Le Clos'})}]}));return()=>{}}};
  const db={collection:name=>name==='chantiers'?sites:{doc:uid=>{if(name!=='kanban'||uid!=='test-user')throw Error('Incorrect Firebase path');return ref}},async runTransaction(fn){let update;const tx={get:async()=>snap(),set:(r,changes,opt)=>{if(r!==ref||!opt?.merge)throw Error('Incorrect transaction');update=changes}};const result=await fn(tx);if(update){merge(state.doc,update);state.writes++;emit()}return result}};
  const auth={currentUser:{uid:'test-user'},onAuthStateChanged(cb){queueMicrotask(()=>cb(this.currentUser));return()=>{}},signInWithEmailAndPassword:async()=>{}};
  window.firebase={apps:[],initializeApp(){this.apps.push({})},auth(){return auth},firestore(){return db}};
  window.INOVTEC_FIREBASE_CONFIG={projectId:'fake'};
 });
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://www.gstatic.com/firebasejs/**',r=>r.fulfill({status:200,contentType:'application/javascript',body:''}));
 await page.route('**/firebase-config.js*',r=>r.fulfill({status:200,contentType:'application/javascript',body:'window.INOVTEC_FIREBASE_CONFIG={projectId:"fake"};'}));
 await page.goto('http://127.0.0.1:8765/REASSORT.html',{waitUntil:'domcontentloaded',timeout:30000});
 await page.waitForFunction(()=>document.querySelector('#syncStatus')?.textContent?.includes('Firebase synchronisé'));
 await page.waitForFunction(()=>document.querySelector('#orderSite')?.options.length>=3);
 check(await page.locator('#kDeliveries').innerText()==='0','Historical supplier receipt miscounted as site delivery');
 check(await page.locator('#kLow').innerText()==='0','Inventory low stock KPI incorrect');
 check(await page.locator('#orderSite').evaluate(e=>e.tagName)==='SELECT','Chantier is not a dropdown');
 check(!(await page.locator('body').innerText()).includes('chiffre d’affaires :'),'Sales wording appears');
 await page.locator('[data-tab="archives"]').click();check(await page.locator('#archiveRows tr').count()===1,'Legacy supplier receipt not preserved');
 await page.locator('[data-tab="demandes"]').click();await page.locator('#orderMaterial').selectOption('m_test');await page.locator('#orderRequester').fill('Agent Martine');await page.locator('#orderSite').selectOption('Améthyste');await page.locator('#orderQty').fill('7');
 await page.locator('#orderForm button[type="submit"]').click();
 await page.waitForFunction(()=>JSON.parse(window.__reassortTest.doc.moduleSyncV1.reassort.payload).orders.length===2);
 let state=await page.evaluate(()=>({d:JSON.parse(window.__reassortTest.doc.moduleSyncV1.reassort.payload),stock:JSON.parse(window.__reassortTest.doc.moduleSyncV1.materiel.payload).items[0].quantity}));
 check(state.d.orders.find(o=>o.workflow==='chantier')?.requester==='Agent Martine','Agent requester not saved');
 check(state.d.orders.some(o=>o.id==='old-order'),'Legacy purchase deleted');
 check(state.stock===9,'Request incorrectly changed inventory');
 check(await page.locator('#kPending').innerText()==='1','Pending site requests not counted');
 await page.locator('[data-tab="livraisons"]').click();await page.locator('#receiptOrder').selectOption({index:1});await page.locator('#receiptQty').fill('2');await page.locator('#receiptDeliveredBy').fill('Céline');await page.locator('#receiveBtn').click();
 await page.waitForFunction(()=>JSON.parse(window.__reassortTest.doc.moduleSyncV1.reassort.payload).deliveries.length===2);
 state=await page.evaluate(()=>({d:JSON.parse(window.__reassortTest.doc.moduleSyncV1.reassort.payload),stock:JSON.parse(window.__reassortTest.doc.moduleSyncV1.materiel.payload).items[0].quantity}));
 check(state.stock===9,'Delivery without stock option modified the inventory');
 check(state.d.deliveries.find(d=>d.kind==='chantier')?.deliveredBy==='Céline','Delivery person not saved');
 check(state.d.orders.find(o=>o.workflow==='chantier')?.status==='partielle','Partial fulfillment not saved');
 check(await page.locator('#kDeliveries').innerText()==='1','First site delivery not counted');
 await page.locator('[data-tab="livraisons"]').click();await page.locator('#receiptOrder').selectOption({index:1});await page.locator('#receiptQty').fill('5');await page.locator('#receiptDeliveredBy').fill('Céline');await page.locator('#receiptDeduct').check();await page.locator('#receiveBtn').click();
 await page.waitForFunction(()=>JSON.parse(window.__reassortTest.doc.moduleSyncV1.reassort.payload).deliveries.length===3);
 state=await page.evaluate(()=>({d:JSON.parse(window.__reassortTest.doc.moduleSyncV1.reassort.payload),stock:JSON.parse(window.__reassortTest.doc.moduleSyncV1.materiel.payload).items[0].quantity}));
 check(state.stock===4,'Opt-in stock deduction not performed exactly once');
 check(state.d.orders.find(o=>o.workflow==='chantier')?.status==='recue','Request not marked delivered');
 check(await page.locator('#kDeliveries').innerText()==='2','Site deliveries count incorrect');
 check(await page.locator('#historyRows tr').count()===2,'History must show two site deliveries only');
 check(await page.locator('#archiveRows tr').count()===1,'Old supplier history changed');
 await page.evaluate(()=>{window.__reassortTest.cache=true;window.__reassortTest.listeners.forEach(cb=>cb({exists:true,data:()=>structuredClone(window.__reassortTest.doc),metadata:{fromCache:true,hasPendingWrites:false}}))});
 check(await page.locator('#saveDraft').isDisabled(),'Offline writes not blocked');
 check(errors.length===0,'Browser JavaScript errors: '+errors.join('; '));
 console.log('OK : demandes des agents, chantier en liste, deux livraisons partielles, archive fournisseur intacte, déduction stock opt-in, aucune vente, protection hors ligne.');
 await context.close();
}catch(e){console.error('ÉCHEC RÉASSORT CHANTIER : '+String(e?.stack||e));process.exitCode=1}finally{await browser.close()}
